### ISSUE TITLE
luci-app-adguardhome编译无法完成

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#1]
adguardhome和 luci-app-adguardhome编译无法完成

**Comment by kenzok8** [comment]
看openwrt- package仓库的提交

**Comment by ghost** [comment]
Setting flags for package librt to hold.
cp -fpR /home/gswangmd/lede/build_dir/target-x86_64_musl/root-x86 /home/gswangmd/lede/build_dir/target-x86_64_musl/root.orig-x86
/home/gswangmd/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/opkg/info/adguardhome.postinst-pkg: line 2: /etc/init.d/AdGuardHome: No such file or directory
postinst script ./usr/lib/opkg/info/adguardhome.postinst has failed with exit code 127
make[2]: *** [package/Makefile:73: package/install] Error 1
make[2]: Leaving directory '/home/gswangmd/lede'
make[1]: *** [package/Makefile:111: /home/gswangmd/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/gswangmd/lede'
make: *** [/home/gswangmd/lede/include/toplevel.mk:230: world] Error 2
gswangmd@gssiserver:~/lede$
