### ISSUE TITLE
package/small-package/firewall/Makefile missing dependency libiptext 

### ISSUE THREAD

**Issue by very20101** [kenzok8/small-package#101]
WARNING: Makefile 'package/small-package/firewall/Makefile' has a dependency on 'libiptext', which does not exist 

WARNING: Makefile 'package/small-package/firewall/Makefile' has a dependency on 'libiptext6', which does not exist 

make[2]: Entering directory '/home/runner/work/Openwrt_retry/Openwrt_retry/workspace/openwrt/scripts/config' 

make[2]: 'conf' is up to date. 

make[2]: Leaving directory '/home/runner/work/Openwrt_retry/Openwrt_retry/workspace/openwrt/scripts/config' 

make[1] diffconfig 

make[2] scripts/config/conf 

WARNING: Makefile 'package/small-package/firewall/Makefile' has a dependency on 'libiptext', which does not exist 

WARNING: Makefile 'package/small-package/firewall/Makefile' has a dependency on 'libiptext6', which does not exist 

make[2]: Entering directory '/home/runner/work/Openwrt_retry/Openwrt_retry/workspace/openwrt/scripts/config' 

make[2]: 'conf' is up to date. 

make[2]: Leaving directory '/home/runner/work/Openwrt_retry/Openwrt_retry/workspace/openwrt/scripts/config' 

make[1] target/compile 

make[2] -C target/linux compile 

WARNING: Makefile 'package/small-package/firewall/Makefile' has a dependency on 'libiptext', which does not exist 

WARNING: Makefile 'package/small-package/firewall/Makefile' has a dependency on 'libiptext6', which does not exist 

make[2]: Entering directory '/home/runner/work/Openwrt_retry/Openwrt_retry/workspace/openwrt/scripts/config' 

make[2]: 'conf' is up to date. 

make[2]: Leaving directory '/home/runner/work/Openwrt_retry/Openwrt_retry/workspace/openwrt/scripts/config' 

make[1] package/compile 

make -r package/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on 

make: *** [/home/runner/work/Openwrt_retry/Openwrt_retry/workspace/openwrt/include/toplevel.mk:231: package/compile] Error 1 

WARNING: Makefile 'package/small-package/firewall/Makefile' has a dependency on 'libiptext', which does not exist 

WARNING: Makefile 'package/small-package/firewall/Makefile' has a dependency on 'libiptext6', which does not exist 

make[2]: Entering directory '/home/runner/work/Openwrt_retry/Openwrt_retry/workspace/openwrt/scripts/config' 

make[2]: 'conf' is up to date. 

make[2]: Leaving directory '/home/runner/work/Openwrt_retry/Openwrt_retry/workspace/openwrt/scripts/config' 

make[1]: Entering directory '/home/runner/work/Openwrt_retry/Openwrt_retry/workspace/openwrt'

**Comment by 596142041** [comment]
这问题修复了么，我现在拉去的还是存在

**Comment by WindyCloudCute** [comment]
我这里也有这个问题 不知道怎么修
