### ISSUE TITLE
transmission-web-control  不能用在新版的transmission上

### ISSUE THREAD

**Issue by Kisoul** [kenzok8/small-package#102]
无法打开管理界面：
404: Not Found
Couldn't find Transmission's web interface files!
Users: to tell Transmission where to look, set the TRANSMISSION_WEB_HOME environment variable to the folder where the web interface's index.html is located.

Package Builders: to set a custom default at compile time, #define PACKAGE_DATA_DIR in libtransmission/platform.c or tweak tr_getClutchDir() by hand.

**Comment by kenzok8** [comment]
https://github.com/kenzok8/compile-package/releases/tag/2023.05.11-2333_x86_64
