### ISSUE TITLE
 Makefile 'package/feeds/small8/naiveproxy/Makefile' has a build dependency on 'gn/host', which does not exist

### ISSUE THREAD

**Issue by lutao114** [kenzok8/small-package#106]
更新安装feeds和make download dll库的时候，都报错
 Makefile 'package/feeds/small8/naiveproxy/Makefile' has a build dependency on 'gn/host', which does not exist

**Comment by kenzok8** [comment]
缺少gn文件，重新拉取下

**Comment by lutao114** [comment]
拉了好多次，都是这样，有没有什么办法直接手动装的
感谢！！
