### ISSUE TITLE
5月份开始编译报错

### ISSUE THREAD

**Issue by dqylyln** [kenzok8/small-package#107]
make[5]: Leaving directory '/root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.110'
cmp -s /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.110/.config /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.110/.config.modules.save && mv /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.110/.config.modules.save /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.110/.config; cp -fpR /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.110/.config /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.110/.config.modules.save
touch /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.110/.modules
make -C image compile TARGET_BUILD=
make[5]: Entering directory '/root/lede/target/linux/x86/image'
make[5]: Nothing to be done for 'compile'.
make[5]: Leaving directory '/root/lede/target/linux/x86/image'
make[4]: Leaving directory '/root/lede/target/linux/x86'
make[3]: Leaving directory '/root/lede/target/linux'
time: target/linux/compile#1864.26#227.81#2092.52
make[2]: Leaving directory '/root/lede'
export MAKEFLAGS= ;make -w -r buildinfo
make[2]: Entering directory '/root/lede'
 make[3] diffconfig buildversion feedsversion
 make[4] scripts/config/conf
make[2]: Leaving directory '/root/lede'
make[2]: Entering directory '/root/lede'
rm -rf /root/lede/staging_dir/target-x86_64_musl/root-x86
make[2]: Leaving directory '/root/lede'
make[2]: Entering directory '/root/lede'
make[2]: *** No rule to make target 'package/system/opkg/host/compile', needed by 'package/compile'.  Stop.
make[2]: Leaving directory '/root/lede'
make[1]: *** [package/Makefile:110: /root/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/root/lede'
make: *** [/root/lede/include/toplevel.mk:231: world] Error 2

切换成https://github.com/kenzok8/openwrt-packages 这个源编译就好了，不知道small-package 在5月份后加入了啥导致的。之前还在https://github.com/coolsnowwolf/lede/issues/11185 提了issue，今天切换回openwrt-packages 就可以了。

[完整错误日志见](https://github.com/coolsnowwolf/lede/files/11411972/build.log)

**Comment by 596142041** [comment]
同样的问题，使用LEDE的加这仓库就报错。原因未知。

**Comment by dqylyln** [comment]
> 同样的问题，使用LEDE的加这仓库就报错。原因未知。

用这个仓库把，https://github.com/kenzok8/openwrt-packages ，这个我试过确定是可以编译成功的。small-package 这个我折腾了没成功，听说删除firewall 和 firewall4 的能成功，但是我尝试删除了firewall 和 firewall4 也没成功，最后无奈只能切回openwrt-packages 的源。

**Comment by yjiawqgj** [comment]
同样，之前是firewall报错，删除了firewall文件夹，然后又报一样的错。

**Comment by kenzok8** [comment]
如果Lean的源码出错，lede根目录下，删除多余的
rm -rf feeds/smpackage/{base-files,dnsmasq,firewall*,fullconenat,libnftnl,nftables,ppp,opkg,ucl,upx,vsftpd-alt,miniupnpd-iptables,wireless-regdb}

**Comment by dqylyln** [comment]
> Lean

确认方法可行，lean 编译验证通过
