### ISSUE TITLE
github.com/openwrt   +  small-package编译错误

### ISSUE THREAD

**Issue by mzfffff** [kenzok8/small-package#110]
make[3]: Entering directory '/home/zz/zz/openwrt/feeds/small8/ddnsgo'
rm -f /home/zz/zz/openwrt/build_dir/target-mipsel_24kc_musl/ddnsgo-5.3.5/.built
touch /home/zz/zz/openwrt/build_dir/target-mipsel_24kc_musl/ddnsgo-5.3.5/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/zz/zz/openwrt/tmp/go-build" GO_MOD_CACHE_DIR="/home/zz/zz/openwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/jeessy2/ddns-go/v5" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/jeessy2/ddns-go/v5/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/zz/zz/openwrt/build_dir/target-mipsel_24kc_musl/ddnsgo-5.3.5" GO_BUILD_DIR="/home/zz/zz/openwrt/build_dir/target-mipsel_24kc_musl/ddnsgo-5.3.5/.go_work/build" GO_BUILD_BIN_DIR="/home/zz/zz/openwrt/build_dir/target-mipsel_24kc_musl/ddnsgo-5.3.5/.go_work/build/bin/linux_mipsle" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/zz/zz/openwrt/staging_dir/target-mipsel_24kc_musl/usr/share/gocode/src" GOOS="linux" GOARCH="mipsle" GO386="" GOAMD64="" GOARM="" GOMIPS="softfloat" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/home/zz/zz/openwrt/build_dir/target-mipsel_24kc_musl/ddnsgo-5.3.5=ddnsgo-5.3.5 -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/zz/zz/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/usr/include -I/home/zz/zz/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/include/fortify -I/home/zz/zz/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/home/zz/zz/openwrt/build_dir/target-mipsel_24kc_musl/ddnsgo-5.3.5=ddnsgo-5.3.5 -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -mips16 -minterlink-mips16" CGO_LDFLAGS="-L/home/zz/zz/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/usr/lib -L/home/zz/zz/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/lib -znow -zrelro" GOPATH="/home/zz/zz/openwrt/build_dir/target-mipsel_24kc_musl/ddnsgo-5.3.5/.go_work/build" GOCACHE="/home/zz/zz/openwrt/tmp/go-build" GOMODCACHE="/home/zz/zz/openwrt/dl/go-mod-cache" GOENV=off /usr/bin/env bash /home/zz/zz/openwrt/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1687205035' -linkmode external -extldflags '-L/home/zz/zz/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/usr/lib -L/home/zz/zz/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"     -installsuffix "softfloat"   -ldflags "-s -w -X m.version=5.3.5 -buildid '1687205035' -linkmode external -extldflags '-L/home/zz/zz/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/usr/lib -L/home/zz/zz/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets

Building targets
runtime/cgo
# runtime/cgo
gcc_mipsx.S: Assembler messages:
gcc_mipsx.S:27: Error: invalid operands `sw $18,12($29)'
gcc_mipsx.S:28: Error: invalid operands `sw $19,16($29)'
gcc_mipsx.S:29: Error: invalid operands `sw $20,20($29)'
gcc_mipsx.S:30: Error: invalid operands `sw $21,24($29)'
gcc_mipsx.S:31: Error: invalid operands `sw $22,28($29)'
gcc_mipsx.S:32: Error: invalid operands `sw $23,32($29)'
gcc_mipsx.S:33: Error: invalid operands `sw $30,36($29)'
gcc_mipsx.S:46: Error: invalid operands `jalr $20'
gcc_mipsx.S:50: Error: invalid operands `lw $18,12($29)'
gcc_mipsx.S:51: Error: invalid operands `lw $19,16($29)'
gcc_mipsx.S:52: Error: invalid operands `lw $20,20($29)'
gcc_mipsx.S:53: Error: invalid operands `lw $21,24($29)'
gcc_mipsx.S:54: Error: invalid operands `lw $22,28($29)'
gcc_mipsx.S:55: Error: invalid operands `lw $23,32($29)'
gcc_mipsx.S:56: Error: invalid operands `lw $30,36($29)'
gcc_mipsx.S:65: Error: invalid operands `lw $31,0($29)'

make[3]: *** [Makefile:97: /home/zz/zz/openwrt/build_dir/target-mipsel_24kc_musl/ddnsgo-5.3.5/.built] Error 1
make[3]: Leaving directory '/home/zz/zz/openwrt/feeds/small8/ddnsgo'
time: package/feeds/small8/ddnsgo/compile#1.00#2.62#1.56
    ERROR: package/feeds/small8/ddnsgo failed to build.
make[2]: *** [package/Makefile:120: package/feeds/small8/ddnsgo/compile] Error 1
make[2]: Leaving directory '/home/zz/zz/openwrt'
make[1]: *** [package/Makefile:114: /home/zz/zz/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zz/zz/openwrt'
make: *** [/home/zz/zz/openwrt/include/toplevel.mk:232：world] 错误 2

**Comment by kenzok8** [comment]
是lean的源码? 删除firewall 与firewall4

**Comment by kenzok8** [comment]
ddns-go缺失
