### ISSUE TITLE
ddns-go依赖丢失

### ISSUE THREAD

**Issue by quanjindeng** [kenzok8/small-package#111]
luci-app-ddns-go这个插件的依赖丢失了

WARNING: Makefile 'package/small-package/luci-app-ddns-go/Makefile' has a dependency on 'ddns-go', which does not exist

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small-package/tree/main/ddnsto

**Comment by quanjindeng** [comment]
> https://github.com/kenzok8/small-package/tree/main/ddnsto

不是同一个，缺的是这个
https://github.com/sirpdboy/luci-app-ddns-go/tree/main/ddns-go

**Comment by kenzok8** [comment]
不好意思，上游仓库变动了，已修复

**Comment by quanjindeng** [comment]
谢谢大佬了
