### ISSUE TITLE
luci-app-ssr-plus依赖"tuic-client"缺失

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#112]
WARNING: Makefile 'package/feeds/small8/luci-app-ssr-plus/Makefile' has a dependency on 'tuic-client', which does not exist

**Comment by small1ee** [comment]
邮件已收到，我会尽快回复

**Comment by dqylyln** [comment]
同样的错误。Already up to date.
Updating feed 'packages' from 'https://github.com/coolsnowwolf/packages' ...
Already up to date.
Updating feed 'luci' from 'https://github.com/coolsnowwolf/luci' ...
Already up to date.
Updating feed 'routing' from 'https://github.com/coolsnowwolf/routing' ...
Already up to date.
Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git' ...
Already up to date.
Updating feed 'kenzo' from 'https://github.com/kenzok8/openwrt-packages' ...
Already up to date.
Updating feed 'small' from 'https://github.com/kenzok8/small' ...
Already up to date.
Create index file './feeds/packages.index'
Create index file './feeds/luci.index'
Create index file './feeds/routing.index'
Create index file './feeds/telephony.index'
Create index file './feeds/kenzo.index'
Create index file './feeds/small.index'
WARNING: Makefile 'package/feeds/small/luci-app-ssr-plus/Makefile' has a dependency on 'tuic-client', which does not exist
Installing all packages from feed packages.
