### ISSUE TITLE
upx error

### ISSUE THREAD

**Issue by ChaingTsung** [kenzok8/small-package#116]
SHELL= flock /home/yoki/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/yoki/openwrt/build_dir/target-aarch64_cortex-a53_musl/luci-app-netspeedtest/.pkgdir/luci-i18n-netspeedtest-zh-cn/. /home/yoki/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
touch /home/yoki/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.luci-i18n-netspeedtest-zh-cn_installed
echo "luci-i18n-netspeedtest-zh-cn" >> /home/yoki/openwrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/luci-app-netspeedtest.default.install
make[3]: Leaving directory '/home/yoki/openwrt/feeds/small8/luci-app-netspeedtest'
time: package/feeds/small8/luci-app-netspeedtest/compile#0.43#0.29#0.70
make[3]: Entering directory '/home/yoki/openwrt/feeds/small8/luci-app-nextcloud'
mkdir -p /home/yoki/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
SHELL= flock /home/yoki/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/yoki/openwrt/build_dir/target-aarch64_cortex-a53_musl/luci-app-nextcloud/.pkgdir/luci-app-nextcloud/. /home/yoki/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
touch /home/yoki/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.luci-app-nextcloud_installed
mkdir -p /home/yoki/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
SHELL= flock /home/yoki/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/yoki/openwrt/build_dir/target-aarch64_cortex-a53_musl/luci-app-nextcloud/.pkgdir/luci-i18n-nextcloud-zh-cn/. /home/yoki/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
touch /home/yoki/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.luci-i18n-nextcloud-zh-cn_installed
make[3]: Leaving directory '/home/yoki/openwrt/feeds/small8/luci-app-nextcloud'
time: package/feeds/small8/luci-app-nextcloud/compile#0.41#0.23#0.59
make[3]: Entering directory '/home/yoki/openwrt/package/openwrt-upx/ucl'
make[3]: Leaving directory '/home/yoki/openwrt/package/openwrt-upx/ucl'
time: package/openwrt-upx/ucl/host-compile#0.50#0.25#0.66
make[3]: Entering directory '/home/yoki/openwrt/feeds/small8/upx'
cp -fpR /home/yoki/openwrt/build_dir/hostpkg/upx-4.1.0/src/upx.out /home/yoki/openwrt/staging_dir/host/bin/upx
cp: cannot stat '/home/yoki/openwrt/build_dir/hostpkg/upx-4.1.0/src/upx.out': No such file or directory
make[3]: *** [Makefile:60: /home/yoki/openwrt/staging_dir/hostpkg/stamp/.upx_installed] Error 1
make[3]: Leaving directory '/home/yoki/openwrt/feeds/small8/upx'
time: package/feeds/small8/upx/host-compile#0.51#0.25#0.68
    ERROR: package/feeds/small8/upx [host] failed to build.
make[2]: *** [package/Makefile:118: package/feeds/small8/upx/host/compile] Error 1
make[2]: Leaving directory '/home/yoki/openwrt'
make[1]: *** [package/Makefile:114: /home/yoki/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/yoki/openwrt'
make: *** [/home/yoki/openwrt/include/toplevel.mk:232：world] 错误 2

**Comment by kenzok8** [comment]
下载地址挂了，已更新
