### ISSUE TITLE
"AdGuardHome"的执行文件路径错误

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#117]
"AdGuardHome"无法启动，执行文件路径由“/usr/bin/AdGuardHome”变为“/usr/bin/AdGuardHome/AdGuardHome”，改后正常。

**Comment by kenzok8** [comment]
![image](https://github.com/kenzok8/small-package/assets/39034242/2cd42521-4ae7-4590-bbf4-600a82ca71ad)
我家里出租房的固件好好的，应该是你自己的问题吧
![image](https://github.com/kenzok8/small-package/assets/39034242/46ff3d80-c417-4b20-b307-76a6840eb0fa)

**Comment by lxg2001** [comment]
我是没有编译进固件，直接下载的

**Comment by ghost** [comment]
> ![image](https://github.com/kenzok8/small-package/assets/39034242/2cd42521-4ae7-4590-bbf4-600a82ca71ad)
> 我家里出租房的固件好好的，应该是你自己的问题吧
> ![image](https://github.com/kenzok8/small-package/assets/39034242/46ff3d80-c417-4b20-b307-76a6840eb0fa)
> 

我是没有编译进固件，直接下载的，都是原样没有改。

**Comment by lxg2001** [comment]
![屏幕截图 2023-08-27 195432](https://github.com/kenzok8/small-package/assets/41837661/57cac182-d5cd-4c9e-8e04-706c32cac3a0)
@kenzok8
