### ISSUE TITLE
After msd_lite is compiled into openwrt firmware, there is no luci, and terminal commands cannot be controlled.

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#120]
**After msd_lite is compiled into openwrt firmware, there is no luci, and terminal commands cannot be controlled. https://github.com/bauw2008/luci-app-msd.git provides a msd_lite available for personal testing.**

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small-package/tree/main/luci-app-msd_lite
 I'm not sure if you have changed luci-app-msd.git and checked compile
