### ISSUE TITLE
miniupnpd-iptables: recursive dependency detected!

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#121]
`tmp/.config-package.in:82862:error: recursive dependency detected!`
`tmp/.config-package.in:82862:   symbol PACKAGE_miniupnpd is selected by PACKAGE_miniupnpd`
`For a resolution refer to Documentation/kbuild/kconfig-language.rst`
`subsection "Kconfig recursive dependency limitations"`
我用的是lean的源码，自带的miniupnpd没有问题，在这个仓库新增miniupnpd-iptables后就出现了

**Comment by kenzok8** [comment]
影响编译吗？应该可以成功的吧
