### ISSUE TITLE
hysteria编译报错

### ISSUE THREAD

**Issue by teddy150420** [kenzok8/small-package#122]
升级到2.0就编译不了，能不能退到1.0版本，支持2.0的客户端还不多，还不太稳定

**Comment by teddy150420** [comment]
https://github.com/apernet/hysteria/tree/hy1

**Comment by kenzok8** [comment]
![image](https://github.com/kenzok8/small-package/assets/39034242/8801a3f6-a9d5-4416-917c-e5a34b5130c3)
https://github.com/kenzok8/small#%E6%B3%A8%E6%84%8F
