### ISSUE TITLE
mosdns编译失败

### ISSUE THREAD

**Issue by lededev** [kenzok8/small-package#124]
报错：
`Patch failed!  Please fix ./patches/100-update-deps.patch!`
看了一眼上游
https://github.com/sbwml/luci-app-mosdns/tree/v5/mosdns/patches
补丁目录里的文件全换了，100到200开头的补丁全部删除了，目前从是201开头的。

**Comment by kenzok8** [comment]
收到，已修正[c6212a2](https://github.com/kenzok8/small-package/commit/c6212a2ca326a693dc742ffc5a42aeebad4b7c1d)

**Comment by lededev** [comment]
编译通过了，运行也正常，thx

**Comment by lededev** [comment]
@kenzok8 mosdns的上游又对patch目录的两个文件进行了变更，因为mosdns升级到了5.3.0
https://github.com/sbwml/luci-app-mosdns/commit/3ef6a85fe0ed975c809696acd9f9c3da97877f99
