### ISSUE TITLE
miniupnpd-iptables 编译出错

### ISSUE THREAD

**Issue by guhill1** [kenzok8/small-package#126]
编译环境 github action 编译,
runs-on: ubuntu-latest

make[3] -C feeds/packages/net/miniupnpd compile
 make[3] -C feeds/small8/miniupnpd-iptables compile
    ERROR: package/feeds/packages/miniupnpd failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on

**Comment by Futurescope** [comment]
九月份一个提交把miniupnpd改名了，不知道为啥改名
