### ISSUE TITLE
github即将不支持subversion

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#133]
svn: E170013: Unable to connect to a repository at URL 'https://github.com/immortalwrt/luci/trunk/applications/luci-app-homeproxy'
svn: E900002: Subversion support temporarily disabled.

GitHub has temporarily disabled Subversion support as part of a planned brownout
in order to give you advance notice of the upcoming permanent removal of
Subversion support on 2024-01-08.
脚本里有些要用到subversion的插件可能会失败

**Comment by xuexijiaoben** [comment]
请问以后只下载某个文件夹用什么命令呀，谢谢啦

**Comment by binge8** [comment]
[看看这里](https://github.com/coolsnowwolf/lede/issues/11757)善用搜索
