### ISSUE TITLE
编译出错，问一下大佬是什么原因造成的，是没有luci-app-upnp这个原因吗？

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#136]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency miniupnpd for luci-app-upnp
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-upnp found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-upnp.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-upnp-zh-cn:
 *      miniupnpd
 * opkg_install_cmd: Cannot install package luci-i18n-upnp-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/cym/desktop/openwrt/r68s'
make[1]: *** [package/Makefile:111: /home/cym/desktop/openwrt/r68s/staging_dir/target-aarch64_generic_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/cym/desktop/openwrt/r68s'
make: *** [/home/cym/desktop/openwrt/r68s/include/toplevel.mk:231: world] Error 2

**Comment by kenzok8** [comment]
这个错误表明你正在尝试安装的 `luci-app-upnp` 和 `luci-i18n-upnp-zh-cn` 包需要 `miniupnpd` 作为依赖，但是这个依赖在你的系统中并未找到。同时，`luci-app-upnp` 包与你的系统架构不兼容。

**Comment by ghost** [comment]
谢谢
