### ISSUE TITLE
gn-2024-01-24-a2e2717e编译失败

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#147]
make[3]: Entering directory '/home/gswangmd/lede/feeds/smpackage/gn'
MAKEFLAGS="" /home/gswangmd/lede/staging_dir/host/bin/ninja  -j1 -C /home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out
ninja: Entering directory `/home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out'
[1/287] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
clang++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++20 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/command_line.cc -o src/base/command_line.o
/bin/sh: 1: clang++: not found
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:58: /home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.built] Error 1
make[3]: Leaving directory '/home/gswangmd/lede/feeds/smpackage/gn'
time: package/feeds/smpackage/gn/host-compile#0.05#0.00#0.08
    ERROR: package/feeds/smpackage/gn [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/smpackage/gn/host/compile] Error 1
make[2]: Leaving directory '/home/gswangmd/lede'
make[1]: *** [package/Makefile:110: /home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/gswangmd/lede'
make: *** [/home/gswangmd/lede/include/toplevel.mk:231: world] Error 2

**Comment by kenzok8** [comment]
5eaabd37fe11e1c09d93babfc1864da197cc98a0

**Comment by ghost** [comment]
问题依旧：

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at a2e2717e Ensure read_file() files are considered by "gn analyze"
Packing checkout...
. /home/gswangmd/lede/include/shell.sh; xzcat /home/gswangmd/lede/dl/gn-2024-01-24-a2e2717e.tar.xz | tar -C /home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/* /home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e
touch /home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.prepared6467909e04da6af8874b4c44792b8885_6664517399ebbbc92a37c5bb081b5c53
python3 /home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/build/gen.py --no-last-commit-position
touch /home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.configured
MAKEFLAGS="" /home/gswangmd/lede/staging_dir/host/bin/ninja  -j1 -C /home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out
ninja: Entering directory `/home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out'
[1/287] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
clang++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++20 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/command_line.cc -o src/base/command_line.o
/bin/sh: 1: clang++: not found
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:58: /home/gswangmd/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.built] Error 1
make[3]: Leaving directory '/home/gswangmd/lede/feeds/smpackage/gn'
time: package/feeds/smpackage/gn/host-compile#4.14#0.87#34.63
    ERROR: package/feeds/smpackage/gn [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/smpackage/gn/host/compile] Error 1
make[2]: Leaving directory '/home/gswangmd/lede'
make[1]: *** [package/Makefile:110: /home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/gswangmd/lede'
make: *** [/home/gswangmd/lede/include/toplevel.mk:231: world] Error 2

**Comment by kenzok8** [comment]
应该是补丁的原因了
