### ISSUE TITLE
v2ray-core官方源包含如何避免冲突

### ISSUE THREAD

**Issue by Calmact** [kenzok8/small-package#15]
官方源中包含v2ray-core，使用`echo 'src-git kenzok8_small_package https://github.com/kenzok8/small-package' >>feeds.conf.default`方式将本仓库加入feeds中。当选中v2ray-core会造成冲突导致编译失败，该如何避免呢？

**Comment by SGPublic** [comment]
强制安装 feeds
`./scripts/feeds install -a` -> `./scripts/feeds install -a -f`

**Comment by kenzok8** [comment]
两者取其一，删除feeds 我文件包里的v2ray-core，运行下./scripts/feeds update -a
./scripts/feeds install -a
