### ISSUE TITLE
编译报错，日志如下

### ISSUE THREAD

**Issue by 596142041** [kenzok8/small-package#153]
hain-x86_64_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"
Finding targets
mkdir -p /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/stamp
go: ../../go.mod **_requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local)_**

Building targets
SHELL= flock /home/lpr/lede/tmp/.root-copy.flock -c 'cp -fpR /home/lpr/lede/build_dir/target-x86_64_musl/luci-app-gowebdav/.pkgdir/luci-app-gowebdav/. /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/'
go: ../../go.mod requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local)

touch /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.luci-app-gowebdav_installed
echo "luci-app-gowebdav" >> /home/lpr/lede/staging_dir/target-x86_64_musl/pkginfo/luci-app-gowebdav.default.install
mkdir -p /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/lpr/lede/tmp/.root-copy.flock -c 'cp -fpR /home/lpr/lede/build_dir/target-x86_64_musl/luci-app-gowebdav/.pkgdir/luci-i18n-gowebdav-zh-cn/. /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.luci-i18n-gowebdav-zh-cn_installed
echo "luci-i18n-gowebdav-zh-cn" >> /home/lpr/lede/staging_dir/target-x86_64_musl/pkginfo/luci-app-gowebdav.default.install
make[3]: Leaving directory '/home/lpr/lede/feeds/kenzok8/luci-app-gowebdav'
time: package/feeds/kenzok8/luci-app-gowebdav/compile#0.35#0.10#0.43
mkdir -p /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/lpr/lede/tmp/.root-copy.flock -c 'cp -fpR /home/lpr/lede/build_dir/target-x86_64_musl/mosdns-5.3.1/.pkgdir/mosdns/. /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/'
make[3]: Entering directory '/home/lpr/lede/feeds/packages/libs/glib2'
touch /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.mosdns_installed
echo "mosdns" >> /home/lpr/lede/staging_dir/target-x86_64_musl/pkginfo/mosdns.default.install
make[3]: Leaving directory '/home/lpr/lede/feeds/packages/net/mosdns'
time: package/feeds/packages/mosdns/compile#0.28#0.17#0.41
make[3]: Entering directory '/home/lpr/lede/feeds/kenzok8/luci-app-speedtest-web'
mkdir -p /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/lpr/lede/tmp/.root-copy.flock -c 'cp -fpR /home/lpr/lede/build_dir/target-x86_64_musl/luci-app-msd_lite/.pkgdir/luci-app-msd_lite/. /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.luci-app-msd_lite_installed
echo "luci-app-msd_lite" >> /home/lpr/lede/staging_dir/target-x86_64_musl/pkginfo/luci-app-msd_lite.default.install
mkdir -p /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/lpr/lede/tmp/.root-copy.flock -c 'cp -fpR /home/lpr/lede/build_dir/target-x86_64_musl/luci-app-msd_lite/.pkgdir/luci-i18n-msd_lite-zh-cn/. /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/lpr/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.luci-i18n-msd_lite-zh-cn_installed
echo "luci-i18n-msd_lite-zh-cn" >> /home/lpr/lede/staging_dir/target-x86_64_musl/pkginfo/luci-app-msd_lite.default.install
make[3]: Leaving directory '/home/lpr/lede/feeds/kenzok8/luci-app-msd_lite'
time: package/feeds/kenzok8/luci-app-msd_lite/compile#0.29#0.10#0.37
make[3]: *** [Makefile:44: /home/lpr/lede/build_dir/target-x86_64_musl/v2ray-plugin-5.15.1/.built] Error 1
make[3]: Leaving directory '/home/lpr/lede/feeds/kenzok8/v2ray-plugin'
time: package/feeds/kenzok8/v2ray-plugin/compile#0.38#0.38#0.74
    ERROR: package/feeds/kenzok8/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:116: package/feeds/kenzok8/v2ray-plugin/compile] Error 1
make[2]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/home/lpr/lede/feeds/kenzok8/luci-app-tcpdump'
make[3]: *** [Makefile:53: /home/lpr/lede/build_dir/target-x86_64_musl/Xray-core-1.8.9/.built] Error 1
make[3]: Leaving directory '/home/lpr/lede/feeds/kenzok8/xray-core'
time: package/feeds/kenzok8/xray-core/compile#0.40#0.34#0.71
    ERROR: package/feeds/kenzok8/xray-core failed to build.
make[2]: *** [package/Makefile:116: package/feeds/kenzok8/xray-core/compile] Error 1

**Comment by kenzok8** [comment]
requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local)
go版本没替换成功

**Comment by 596142041** [comment]
> requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local) go版本没替换成功
这要怎么修复呢？使用的LEDE的源码编译的

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small/issues/148#issuecomment-1988764608
