### ISSUE TITLE
ssr++支持添加wireguard节点但是不能用

### ISSUE THREAD

**Issue by 13736171140** [kenzok8/small-package#156]
好不容易把cidr改成cidr4，cidr6解决了wireguard无法保存问题，但是wireguard运行之后不能科学上网，也不知道现在是哪位大佬在更新维护ssr++

**Comment by kenzok8** [comment]
请给上游仓库提交issues
[ssr](https://github.com/fw876/helloworld)

**Comment by 13736171140** [comment]
> 请给上游仓库提交issues [ssr](https://github.com/fw876/helloworld)



> 请给上游仓库提交issues [ssr](https://github.com/fw876/helloworld)

哦，上游都不知道在哪，哈哈

**Comment by 13736171140** [comment]
> 请给上游仓库提交issues [ssr](https://github.com/fw876/helloworld)

哦，上游都不知道在哪，哈哈
