### ISSUE TITLE
申请添加luci-app-fakemesh（很好用很傻瓜的mesh组网插件）

### ISSUE THREAD

**Issue by clawneo** [kenzok8/small-package#158]
https://github.com/x-wrt/com.x-wrt/tree/master/luci-app-fakemesh

fakemesh简介
fakemesh是一种网络拓扑结构，由一个控制器（AC）和一个或多个有线AP（Wired AP）和卫星（Agent）组成。它是一种混合了无线Mesh和AC+AP两种组网模式的混合网络，其中，有线AP通过网线和控制器（AC）相连，而卫星（Agent）则通过无线STA方式接入，共同构成一个无线（包括有线）覆盖网络。

fakemesh的部署确实相对较为方便，只需要将节点设备连接到正确的网络，并设置节点设备的角色，Mesh ID等信息即可。因为fakemesh结合了无线Mesh和AC+AP两种组网模式，所以也可以很方便地进行混合组网，提高了网络的覆盖范围和可靠性。

目前[X-WRT](https://github.com/x-wrt/x-wrt)默认集成了fakemesh功能

**Comment by kenzok8** [comment]
好的，安排

**Comment by clawneo** [comment]
> 好的，安排

谢谢~
