### ISSUE TITLE
mosdns

### ISSUE THREAD

**Issue by geryson911** [kenzok8/small-package#16]
勾选这个插件编译就不成功,希望能修复下
错误代码
 * check_data_file_clashes: Package luci-app-mosdns wants to install file /home/shenwenfan/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/mosdns
        But that file is already provided by package  * mosdns
 * opkg_install_cmd: Cannot install package luci-app-mosdns.
 * check_data_file_clashes: Package luci-app-mosdns wants to install file /home/shenwenfan/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/mosdns
        But that file is already provided by package  * mosdns
 * opkg_install_cmd: Cannot install package luci-i18n-mosdns-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255

**Comment by fangjia052** [comment]
我也有相同问题

**Comment by a7502** [comment]
我勾选也编译失败，去掉就好了

**Comment by kenzok8** [comment]
已修复#27

**Comment by kenzok8** [comment]
#27

**Comment by kenzok8** [comment]
其实是Lean源码里有mosdns了，所以编译过程里才会出错
rm -rf feeds/packages/net/mosdns
编译就能过了

**Comment by lgs2007m** [comment]
> 其实是Lean源码里有mosdns了，所以编译过程里才会出错 rm -rf feeds/packages/net/mosdns 编译就能过了

老大，测试了删除源码的mosdns，编译还是出错：
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/include/toplevel.mk:230: world] Error 1
WARNING: Makefile 'package/feeds/small8/luci-app-mosdns/Makefile' has a dependency on 'mosdns', which does not exist

在恩山看到了相同问题帖子“[ctc18.06编译MosDNS错误](https://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&ptid=8226831&pid=16902242)”，有个解决办法是删除同时用自定义库的mosdns替换，编译就成功了。我小白不懂其中的原理……

`rm -rf ./feeds/packages/net/mosdns && cp -rf ./feeds/small8/mosdns ./feeds/packages/net/mosdns`
