### ISSUE TITLE
编译shadowsocksr-libev报错

### ISSUE THREAD

**Issue by wukibaka** [kenzok8/small-package#163]
使用的[immortalwrt](https://github.com/immortalwrt/immortalwrt)master分支
checking for pcre-config... pcre-config
checking for pcre headers in ... not found
checking for library containing pcre_exec... no
configure: error: Cannot find pcre library. Configure --with-pcre=DIR
make[3]: *** [Makefile:67: /workdir/openwrt/build_dir/target-aarch64_generic_musl/shadowsocksr-libev-2.5.3/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/workdir/openwrt/feeds/smallpackage/shadowsocksr-libev'
time: package/feeds/smallpackage/shadowsocksr-libev/compile#24.82#0.88#27.47
    ERROR: package/feeds/smallpackage/shadowsocksr-libev failed to build.
make[2]: *** [package/Makefile:129: package/feeds/smallpackage/shadowsocksr-libev/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:123: /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:233: world] Error 2
Error: Process completed with exit code 2.

**Comment by kenzok8** [comment]
[immortalwrt](https://github.com/immortalwrt/immortalwrt)源码net下有shadowsocksr-libev，而且我small仓库是能正常编译的
[自己看](https://github.com/kenzok8/small/releases/tag/13-arm_cortex-a7)

**Comment by wukibaka** [comment]
奇怪 今天又能正常编译了

**Comment by wukibaka** [comment]
helloworld仓库中ssr-libev的makefile
depends把libpcre换成了libpcre2

**Comment by lededev** [comment]
把pcre换成pcre2不是不行，但需要在shadowsocksr-libev修改源代码，把对libpcre的调用代码，修改为调用libpcre2的，简单的换链接库是不行的。
openwrt主干已经摘除了不再维护的pcre，全部采用pcre2，所以shadowsocksr-libev会因为没有了libpcre链接失败，最快解决办法是把pcre收录进small-package里，这样的话，什么都不用改。
符合openwrt方式的办法就是改代码升级到pcre2，奈何shadowsocksr-libev已经无人维护，想提交都没地方提交。就连gcc13的编译补丁我还是提交在这里的。而pcre升级到pcre2我也没弄过，目前暂时用的前面一个办法，在feeds里加了个oldpack源目录，把pcre放进去了。

**Comment by lededev** [comment]
这是[shadowsocks-libev: convert to PCRE2](https://git.openwrt.org/?p=feed/packages.git;a=commit;h=db305165c9a0b9b69a83f6379d0994c3708d58e8)的改动，从技术上看移植没啥大问题，就是有一定工作量。对这种没有什么维护的包而言不太划算。

**Comment by wukibaka** [comment]
上游关于pcre更新pcre2做出的修改非常多，并不只是将makefile中depends的libpcre换成libpcre2
![Screenshot_2024-05-18-08-25-27-283_com.github.android.jpg](https://github.com/kenzok8/small-package/assets/51240031/8af60514-ed34-401e-b24c-6e5e06c44845)
