### ISSUE TITLE
编译新版AdguardHome需要go1.22.3版本，但是https://github.com/kenzok8/golang这个仓库的go为1.22.2

### ISSUE THREAD

**Issue by 1WuNeiGui** [kenzok8/small-package#166]
K大你好，最近AdguardHome更新到了 v0.107.50版本，在拉取最新源码进行编译时发现AdguardHome编译出错，单线程编译发现v0.107.50需要go1.22.3，但是https://github.com/kenzok8/golang这个仓库里面的go是1.22.2版本，希望K大可以更新一下，辛苦K大

**Comment by kenzok8** [comment]
已更新
https://github.com/kenzok8/golang/commit/e2eb1e7381c998ae998b2232f42a2e236a8f83cc
