### ISSUE TITLE
缺少的依赖如何手动添加

### ISSUE THREAD

**Issue by s1u** [kenzok8/small-package#172]
`WARNING: Makefile 'package/feeds/smpackage/natflow/Makefile' has a dependency on 'urllogger', which does not exist` 
虽然没有选择这个相关部分，暂时不影响编译。但本着执着不逃避，如何解决这个问题？

能手动添加么？如何操作？谢谢。

**Comment by kenzok8** [comment]
rm -rf package/feeds/smpackage/natflow
或者找到urllogger 放在smpackage目录
