### ISSUE TITLE
求助，lede版opwrt加入小包后编译报错

### ISSUE THREAD

**Issue by xiaojiejieouo** [kenzok8/small-package#182]
lede原版编译正常，根据教程加入主页两个命令后编译报错

**Comment by kenzok8** [comment]
没报错日志，没截图，啥都没有，我咋知道？

**Comment by xiaojiejieouo** [comment]
> 没报错日志，没截图，啥都没有，我咋知道？

实在抱歉，我也是刚刚学会编译，我的具体操作是

编译lede opwrt，显示成功后
按照主页使用方式：sed -i '$a src-git smpackage https://github.com/kenzok8/small-package' feeds.conf.default
rm -rf feeds/smpackage/{base-files,dnsmasq,firewall*,fullconenat,libnftnl,nftables,ppp,opkg,ucl,upx,vsftpd*,miniupnpd-iptables,wireless-regdb}

./scripts/feeds update -a
./scripts/feeds install -a
make defconfig
在成功编译的基础上不做任何更改，编译到最后会报错无法成功输出

另外如果i您可以告诉我一下如何提供报错日志我会补上，我从网上查了一个单线程编译，但是未输出日志
实在抱歉，是我贸然提出了奇怪的问题，但是确实是刚刚接触，十分抱歉
