### ISSUE TITLE
imm和openwrt主线启用了apk，导致好多插件无法正常编译。

### ISSUE THREAD

**Issue by ZqinKing** [kenzok8/small-package#191]
如题。小伙伴遇到类似问题，现阶段建议关闭USE_APK保持使用opkg进行固件编译。等大佬们适配的差不多了，再使用apk。

**Comment by shaoyifan** [comment]
怎么关闭apk啊，我编译openclash 提示版本非法，估计也是apk的原因

**Comment by ZqinKing** [comment]
> 怎么关闭apk啊，我编译openclash 提示版本非法，估计也是apk的原因

# CONFIG_USE_APK is not set
# CONFIG_PACKAGE_apk-mbedtls is not set

**Comment by ZqinKing** [comment]
> 怎么关闭apk啊，我编译openclash 提示版本非法，估计也是apk的原因

\# CONFIG_USE_APK is not set
\# CONFIG_PACKAGE_apk-mbedtls is not set

**Comment by shaoyifan** [comment]
好的，感谢
