### ISSUE TITLE
劳烦大佬添加一下passwall的新依赖geoview

### ISSUE THREAD

**Issue by ZqinKing** [kenzok8/small-package#195]
项目源码：https://github.com/snowie2000/geoview
插件源码：https://github.com/xiaorouji/openwrt-passwall-packages/tree/main/v2ray-geoview
如果可以的话，麻烦大大把tcping一并更新一下，当前small-package中的tcping不支持IPv6。
可以使用pw中的https://github.com/xiaorouji/openwrt-passwall-packages/tree/main/tcping。
感谢，抱拳

**Comment by kenzok8** [comment]
已添加上游，但是tcping 是Lienol的仓库，版本更老，你确定该版本是支持ipv6？

**Comment by ZqinKing** [comment]
> 已添加上游，但是tcping 是Lienol的仓库，版本更老，你确定该版本是支持ipv6？

是的，已经测试过了。代码也看过。Lienol的使用了getaddrinfo是支持IPv6的。

**Comment by ZqinKing** [comment]
> 已添加上游，但是tcping 是Lienol的仓库，版本更老，你确定该版本是支持ipv6？

Mattraks的gethostbyname只支持解析V4地址

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small/commit/e61ce16db64ba3d573138a197b79fd6b7d2b56dc
我刚刚试着修改了代码，编译也没出错，但是没去测试是否支持ipv6，你要么测试下
https://github.com/kenzok8/litte/releases/tag/199-x86_64

**Comment by ZqinKing** [comment]
> [kenzok8/small@e61ce16](https://github.com/kenzok8/small/commit/e61ce16db64ba3d573138a197b79fd6b7d2b56dc)
> 我刚刚试着修改了代码，编译也没出错，但是没去测试是否支持ipv6，你要么测试下
> https://github.com/kenzok8/litte/releases/tag/199-x86_64

感谢大佬，晚点我编一下试试

**Comment by ZqinKing** [comment]
> [kenzok8/small@e61ce16](https://github.com/kenzok8/small/commit/e61ce16db64ba3d573138a197b79fd6b7d2b56dc)
> 我刚刚试着修改了代码，编译也没出错，但是没去测试是否支持ipv6，你要么测试下
> https://github.com/kenzok8/litte/releases/tag/199-x86_64

还没试，不过看代码好像jlyo的应该是支持的才对。之前只看了Mattraks的，没注意具体是哪个编译的了，三个库我都试一下吧。

**Comment by ZqinKing** [comment]
> [kenzok8/small@e61ce16](https://github.com/kenzok8/small/commit/e61ce16db64ba3d573138a197b79fd6b7d2b56dc) 我刚刚试着修改了代码，编译也没出错，但是没去测试是否支持ipv6，你要么测试下 https://github.com/kenzok8/litte/releases/tag/199-x86_64

试了下不行哦，Mattraks的不支持V6

**Comment by kenzok8** [comment]
jlyo的仓库哦 源码
[  URL:=https://github.com/jlyo/tcping](https://github.com/kenzok8/small-package/blob/4f20be79c59eaee85f4f3f7f6327b7a6251038ed/tcping/Makefile#L26)
