### ISSUE TITLE
luci-app-adguardhome编译错误

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#2]
Setting flags for package librt to hold.
cp -fpR /home/gswangmd/lede/build_dir/target-x86_64_musl/root-x86 /home/gswangmd/lede/build_dir/target-x86_64_musl/root.orig-x86
/home/gswangmd/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/opkg/info/adguardhome.postinst-pkg: line 2: /etc/init.d/AdGuardHome: No such file or directory
postinst script ./usr/lib/opkg/info/adguardhome.postinst has failed with exit code 127
make[2]: *** [package/Makefile:73: package/install] Error 1
make[2]: Leaving directory '/home/gswangmd/lede'
make[1]: *** [package/Makefile:111: /home/gswangmd/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/gswangmd/lede'
make: *** [/home/gswangmd/lede/include/toplevel.mk:230: world] Error 2
gswangmd@gssiserver:~/lede$

貌似缺少 install 段

**Comment by kenzok8** [comment]
重新拉下

**Comment by ghost** [comment]
重新拉去后照样编译不过去。

**Comment by kenzok8** [comment]
make distclean重新来一次
dl文件夹里看下是否拉取了adguardhome-0.107.0-b.11.tar.xz

**Comment by ghost** [comment]
拉取了的，就是始终编译不过去。

**Comment by kenzok8** [comment]
https://github.com/kenzok8/openwrt-packages/issues/205#issuecomment-922420756

**Comment by kenzok8** [comment]
![image](https://user-images.githubusercontent.com/39034242/134051399-d5af914b-4628-4e8e-a235-52b108b87f13.png)
本地编译也没问题啊

**Comment by ghost** [comment]
是能生成ipk，但是打包成固件时就出错了。
