### ISSUE TITLE
luci-theme-argonne主题的Makefile文件好像有错误，导致编译后登录界面不能显示背景图

### ISSUE THREAD

**Issue by lgs2007m** [kenzok8/small-package#22]
luci-theme-argonne的[Makefile](https://github.com/kenzok8/small-package/blob/main/luci-theme-argonne/Makefile)中有一行：
`[ -f /usr/lib/lua/luci/view/themes/argon/out_header_login.htm ] && mv -f /usr/lib/lua/luci/view/themes/argon/out_header_login.htm /usr/lib/lua/luci/view/header_login.htm`
其中的argon未修改为argonne，导致编译后登录界面不能显示背景图。通过手动修改移动路由器的/usr/lib/lua/luci/view/themes/argon/out_header_login.htm到/usr/lib/lua/luci/view/header_login.htm后就正常了。

请大佬检查修改下。

**Comment by lgs2007m** [comment]
https://github.com/kenzok8/openwrt-packages 下luci-theme-argonne的[Makefile](https://github.com/kenzok8/openwrt-packages/blob/master/luci-theme-argonne/Makefile)也是一样的。

**Comment by lgs2007m** [comment]
不是这个源码库的问题，我去源码库反馈 https://github.com/kenzok78/luci-theme-argonne

**Comment by kenzok8** [comment]
颜色在Argonne 主题设置里把
明亮模式下
#787399改成默认的#5e72e4
![360截图17340724171846](https://user-images.githubusercontent.com/39034242/156486679-58d18119-0de9-4e0d-b76c-7d317eb2f95f.png)

暗黑模式下
#787399改成默认的 #483d8b

**Comment by lgs2007m** [comment]
> 颜色在Argonne 主题设置里把 明亮模式下 #787399改成默认的#5e72e4 ![360截图17340724171846](https://user-images.githubusercontent.com/39034242/156486679-58d18119-0de9-4e0d-b76c-7d317eb2f95f.png)
> 
> 暗黑模式下 #787399改成默认的 #483d8b


大佬你好，这个颜色可以设置没什么问题，我想反映主题登录界面显示不正常，没有背景图。我去源码库那边提了issue https://github.com/kenzok78/luci-theme-argonne/issues/3

![bg1](https://user-images.githubusercontent.com/22903593/156487307-ee9a1066-4898-48c7-b4c7-5029d6fdc568.jpg)

**Comment by kenzok8** [comment]
已修复

**Comment by lgs2007m** [comment]
> 已修复

早上就看到已修改了，谢谢大佬
