### ISSUE TITLE
lede源码编译后，切换edge主题，屏幕一片白，无法操作

### ISSUE THREAD

**Issue by molun** [kenzok8/small-package#24]
是否是主题不兼容导致，编译时应该怎么处理呢？

**Comment by kenzok8** [comment]
edge是适配21.02源码

**Comment by kenzok8** [comment]
ssh连接路由 
1.删除错误主题
opkg info luci-theme*
opkg remove luci-theme- edge

2. openwrt主页系统下多余的无效主题名
nano /etc/config/luci
删除edge

3 /usr/lib/lua/luci/view/themes/
目录下删除失效包- edge

**Comment by xrcuo** [comment]
edge(以后有没有考虑适配新版本这个主题？)
