### ISSUE TITLE
Mosdns支持哪个版本的内核，5.4  5.15编译不成功

### ISSUE THREAD

**Issue by FMJYY23** [kenzok8/small-package#27]
Mosdns支持哪个版本的内核，5.4  5.15编译不成功

**Comment by kenzok8** [comment]
你用的是Lean源码吧？与内核无关，我刚刚手动编译21.02源码是没问题的
![image](https://user-images.githubusercontent.com/39034242/157873488-2bbae4f0-5a9c-468c-bac9-67d90ff24dff.png)

**Comment by FMJYY23** [comment]
好的谢谢

**Comment by jy02919061** [comment]
Lean源码有问题吗

**Comment by a7502** [comment]
老大用的是那个源码呢？我用的lean源码也编译不成功。

**Comment by a7502** [comment]
lean的源码加kiddin9插件库，里面也有mosdns，编译没问题。用大佬你的就不行，不知道问题出在那。

**Comment by kenzok8** [comment]
已修复 #[luci-app-mosdns/po/zh-cn/mosdns.po](https://github.com/kenzok8/small-package/commit/125f9ab3a5f5c610e51bda45aa5cd47a0e09b19e#diff-beb1bd90f17e89ea8c74a6121ea3b953b1113bd97f67ad85b6048c1bd314024e)  100644 → 100755

**Comment by kenzok8** [comment]
已修复 #https://github.com/kenzok8/small-package/commit/d6471ba77cdb3784fed22be5061d3c992a08d2c2

**Comment by a7502** [comment]
还是不能编译成功，不选择这插件就ok

**Comment by kenzok8** [comment]
Lean 源码下运行
rm -rf feeds/packages/net/mosdns
