### ISSUE TITLE
求助怎么单独加需要的插件

### ISSUE THREAD

**Issue by annce** [kenzok8/small-package#30]
使用方式（三选一）：
先cd进package目录，然后执行
 git clone https://github.com/kenzok8/small-package
或者添加下面代码到feeds.conf.default文件
 src-git small8 https://github.com/kenzok8/small-package
lede/下运行 或者openwrt/下运行
git clone https://github.com/kenzok8/small-package package/small-package

这三个办法，到最后都会出现编译错误，请问怎么单独在里面选择需要的编译，而不是把整个插件库拉进去再选择

**Comment by kenzok8** [comment]
svn co https://github.com/kenzok8/small-package/trunk/luci-app-adguardhome

**Comment by annce** [comment]
> svn co https://github.com/kenzok8/small-package/trunk/luci-app-adguardhome

请问这个命令在哪个目录下运行cd lede还是 别的啥
