### ISSUE TITLE
麻烦有大佬帮忙看下这是什么错误吗？

### ISSUE THREAD

**Issue by a786458540** [kenzok8/small-package#34]
Patch failed!  Please fix ./patches/010-go-1.18.patch!
make[3]: *** [Makefile:116: /home/cy/lede/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.prepared_1abae205142d6c291667cbc7940935fa_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/cy/lede/feeds/small/v2ray-core'
time: package/feeds/small/v2ray-core/compile#0.25#0.16#0.39
    ERROR: package/feeds/small/v2ray-core failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/v2ray-core/compile] Error 1
make[2]: Leaving directory '/home/cy/lede'
make[1]: *** [package/Makefile:110: /home/cy/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/cy/lede'
make: *** [/home/cy/lede/include/toplevel.mk:230：world] 错误 2

**Comment by kenzok8** [comment]
feeds/small/v2ray-core/compile不是明显的吗？v2ray内核编译出错
