### ISSUE TITLE
大佬， small-package和openwrt-packages有什么区别哈

### ISSUE THREAD

**Issue by leopardciaw** [kenzok8/small-package#36]
另外，lean源，使用哪个更合适。
这两个包是不是同步更新哈。

感谢一直的坚持更新！

**Comment by kenzok8** [comment]
small-package 就像esir固件的高大全版，插件多点，激进点，HASH值都用skip，再用命令自动获取releases最新版本。
openwrt-packages 就是佛跳墙版，保留最常用的，如果Lean大，或者Lienol大的固件源码里有的，我一般不会再录入的。
如果追求稳定还是openwrt- packages仓库吧

**Comment by leopardciaw** [comment]
> small-package 就像esir固件的高大全版，插件多点，激进点，HASH值都用skip，再用命令自动获取releases最新版本。 openwrt-packages 就是佛跳墙版，保留最常用的，如果Lean大，或者Lienol大的固件源码里有的，我一般不会再录入的。 如果追求稳定还是openwrt- packages仓库吧

谢谢大佬回复。可以关闭了。
