### ISSUE TITLE
同步仓库问题！

### ISSUE THREAD

**Issue by jinjin327** [kenzok8/small-package#48]
你好,对应.github/workflows目录下的yml工作流文件里的ACCESS_TOKEN名称（依据自己yml文件修改）,这句话没看懂，请大神指教。

**Comment by kenzok8** [comment]
ACCESS_TOKEN  就是我页面说明里建立的TOKEN 的名称，如果完全参考我的就是ACCESS_TOKEN
依据你取的名字去更改而已
