### ISSUE TITLE
语法错误

### ISSUE THREAD

**Issue by Thanf-code** [kenzok8/small-package#5]
![Screenshot_20210927_190337](https://user-images.githubusercontent.com/82493550/134996017-233b866e-3692-4ee0-a18e-ef14ea864590.jpg)

**Comment by Thanf-code** [comment]
好像是某些插件相互冲突

**Comment by kenzok8** [comment]
上游ssr-plus 语法错误导致的，我昨天忙，没来得及及时更新

**Comment by Thanf-code** [comment]
> 上游ssr-plus 语法错误导致的，我昨天忙，没来得及及时更新

好像不是ssrp的问题， 是其他插件的问题，因为我没有删除ssrp，用lean源码编译成功了
