### ISSUE TITLE
mosdns报错

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#51]
WARNING: Makefile 'package/feeds/small8/luci-app-mosdns/Makefile' has a dependency on 'mosdns_neo', which does not exist

**Comment by jinjin327** [comment]
同样

**Comment by binge8** [comment]
同样

**Comment by kenzok8** [comment]
修复了

**Comment by ghost** [comment]
问题依然存在
Collecting package info: done
WARNING: Makefile 'package/feeds/small8/luci-app-mosdns/Makefile' has a dependency on 'mosdns_neo', which does not exist
WARNING: Makefile 'package/feeds/small8/luci-app-xray/Makefile' has a dependency on 'kmod-nft-tproxy', which does not exist

**Comment by kenzok8** [comment]
rm -rf ./feeds && ./scripts/feeds update -a && ./scripts/feeds install -a && rm -rf ./tmp && make menuconfig
重新拉取下哦

**Comment by ghost** [comment]
> rm -rf ./feeds && ./scripts/feeds update -a && ./scripts/feeds install -a && rm -rf ./tmp && make menuconfig 重新拉取下哦

结果一样：
WARNING: Makefile 'package/feeds/small8/luci-app-mosdns/Makefile' has a dependency on 'mosdns_neo', which does not exist
WARNING: Makefile 'package/feeds/small8/luci-app-xray/Makefile' has a dependency on 'kmod-nft-tproxy', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed gssipackages.
Installing all packages from feed small8.
WARNING: Not overriding core package 'mbedtls'; use -f to force
WARNING: Not overriding core package 'vsftpd-alt'; use -f to force
gswangmd@WMD-HOME:~/lede$  rm -rf ./tmp
gswangmd@WMD-HOME:~/lede$ make menuconfig
Collecting package info: done
Collecting target info: done
WARNING: Makefile 'package/feeds/small8/luci-app-mosdns/Makefile' has a dependency on 'mosdns_neo', which does not exist
WARNING: Makefile 'package/feeds/small8/luci-app-xray/Makefile' has a dependency on 'kmod-nft-tproxy', which does not exist

**Comment by ghost** [comment]
Lede代码，
建议重新命名这里的mosdos目录，修改部分代码。

**Comment by ghost** [comment]
无论怎么重做，始终存在错误：
WARNING: Makefile 'package/feeds/small8/luci-app-mosdns/Makefile' has a dependency on 'mosdns_neo', which does not exist

**Comment by a7502** [comment]
feeds/small8/luci-app-mosdns/Makefile 里面的+mosdns_neo 后面的_neo去掉，变成+mosdns，就不报错了

**Comment by kenzok8** [comment]
/lede/feeds/packages/net/ 把L大的源码自带的mosdns删除

或者命令 rm -rf feeds/packages/net/mosdns

**Comment by ghost** [comment]
删除了一样

**Comment by zhengqiang** [comment]
一样，一直报错。用L大的固件

**Comment by lee29** [comment]
`    - name: 去除重复应用包
      run: |
         cd openwrt
      
 
         sudo rm -rf ./feeds/packages/net/mosdns && cp -rf ./feeds/kenzo/mosdns ./feeds/packages/net/mosdns
         sed -i 's/mosdns_neo/mosdns/g' ./feeds/kenzo/luci-app-mosdns/Makefile
         sed -i 's/mosdns_neo/mosdns/g' ./feeds/kenzo/mosdns/Makefile
         sed -i 's/mosdns_neo/mosdns/g' ./feeds/packages/net/mosdns/Makefile

               
    - name: 安装 feeds 应用包
      run: cd openwrt && ./scripts/feeds install -a`
kenzo改为small8或者ssh进去找一下

**Comment by ghost** [comment]
感谢，已经好了！

**Comment by zhengqiang** [comment]
21.02 还是编译失败。

**Comment by nagastone** [comment]
L大最新源码编译失败
     sudo rm -rf ./feeds/packages/net/mosdns && cp -rf ./feeds/kenzo/mosdns ./feeds/packages/net/mosdns
     sed -i 's/mosdns_neo/mosdns/g' ./feeds/kenzo/luci-app-mosdns/Makefile
     sed -i 's/mosdns_neo/mosdns/g' ./feeds/kenzo/mosdns/Makefile
     sed -i 's/mosdns_neo/mosdns/g' ./feeds/packages/net/mosdns/Makefile
这一步做过之后拉取不报错，但最后编译报错，还是mosdns的neo依赖

**Comment by TaoRone** [comment]
10.03，再次出现该问题
