### ISSUE TITLE
请问最新的luci-app-ssr-plus，不能正常订阅，一订阅很多正常的节点说是无效的节点，然后删除了

### ISSUE THREAD

**Issue by netlovehf** [kenzok8/small-package#53]
请问最新的luci-app-ssr-plus，不能正常订阅，一订阅很多正常的节点说是无效的节点，然后删除了，以前的luci-app-ssr-plus正常的

**Comment by netlovehf** [comment]
![911](https://user-images.githubusercontent.com/48405188/178092696-ad06be06-9220-4273-9a1b-43857b7f2bda.jpg)

**Comment by netlovehf** [comment]
![2424](https://user-images.githubusercontent.com/48405188/178092776-bd1c98aa-0481-4b6e-880f-505b1226c5ad.jpg)

**Comment by yuzhe1129** [comment]
发错地方了，你再lean那发错了，这里又发，问隔壁啊
