### ISSUE TITLE
缺少依赖啊。

### ISSUE THREAD

**Issue by sjkhsl** [kenzok8/small-package#57]
WARNING: Makefile 'package/feeds/small8/linkease/Makefile' has a dependency on 'ffmpeg-remux', which does not exist
WARNING: Makefile 'package/feeds/small8/luci-app-store/Makefile' has a dependency on 'luci-lib-taskd', which does not exist
WARNING: Makefile 'package/feeds/small8/luci-app-xray/Makefile' has a dependency on 'kmod-nft-tproxy', which does not exist

**Comment by X-Firefly** [comment]
一样
Create index file './feeds/small.index' 
WARNING: Makefile 'package/feeds/small8/linkease/Makefile' has a dependency on 'ffmpeg-remux', which does not exist
WARNING: Makefile 'package/feeds/small8/luci-app-store/Makefile' has a dependency on 'luci-lib-taskd', which does not exist
WARNING: Makefile 'package/feeds/small8/luci-app-xray/Makefile' has a dependency on 'kmod-nft-tproxy', which does not exist

**Comment by sjkhsl** [comment]
> 一样 Create index file './feeds/small.index' WARNING: Makefile 'package/feeds/small8/linkease/Makefile' has a dependency on 'ffmpeg-remux', which does not exist WARNING: Makefile 'package/feeds/small8/luci-app-store/Makefile' has a dependency on 'luci-lib-taskd', which does not exist WARNING: Makefile 'package/feeds/small8/luci-app-xray/Makefile' has a dependency on 'kmod-nft-tproxy', which does not exist

解决了吗？从别的仓库下载过来也不行～头疼～

**Comment by sjkhsl** [comment]
WARNING: Makefile 'package/feeds/small8/linkease/Makefile' has a dependency on 'ffmpeg-remux', which does not exist
WARNING: Makefile 'package/feeds/small8/luci-app-store/Makefile' has a dependency on 'luci-lib-taskd', which does not exist
WARNING: Makefile 'package/feeds/luci/applications/luci-app-webdav/Makefile' has a dependency on 'webdav-hacdias', which does not exist
WARNING: Makefile 'package/feeds/small8/luci-app-xray/Makefile' has a dependency on 'kmod-nft-tproxy', which does not exist

缺的越来越多了！

**Comment by jinjin327** [comment]
一样，哈哈

**Comment by Oda921** [comment]
WARNING: Makefile 'package/small-package/luci-app-xray/Makefile' has a dependency on 'kmod-nft-tproxy', which does not exist
我用的是lede源码编译的，提示缺少依赖
