### ISSUE TITLE
argonne主题异常，是与x-wrt一起编译的。

### ISSUE THREAD

**Issue by ZqinKing** [kenzok8/small-package#67]
Error
Unhandled exception during request dispatching
/usr/lib/lua/luci/ucodebridge.lua:23: /usr/lib/lua/luci/template.lua:181: Failed to execute template 'themes/argonne/header'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/argonne/heade..."]:18: attempt to get length of local 'request2' (a nil value)
stack traceback:
[string "/usr/lib/lua/luci/view/themes/argonne/heade..."]:18: in main chunk

In error(), file [C]
called from function run (/usr/lib/lua/luci/ucodebridge.lua:23)
called from function [anonymous function] (/usr/lib/lua/luci/ucodebridge.lua:37)
In [anonymous function](), file /usr/share/ucode/luci/runtime.uc, line 123, byte 10:
  called from function [arrow function] (/usr/share/ucode/luci/runtime.uc:131:63)
  called from function render ([C])
  called from function [anonymous function] (/usr/share/ucode/luci/runtime.uc:131:64)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:924:38)
  called from anonymous function (/www/cgi-bin/luci:39:12)

 `            die(ex);`
  Near here --------^

**Comment by ZqinKing** [comment]
好像明白了。x-wrt是22.03的分支，是不是不支持呀？

**Comment by kenzok8** [comment]
main默认支持luci-18.06
