### ISSUE TITLE
编译alist错误，望大佬指点，感激感激

### ISSUE THREAD

**Issue by JackyLeeGM** [kenzok8/small-package#69]
Applying ./patches/001-disable-delete-of-temp-directory-at-startup.patch using plaintext: 
patching file internal/bootstrap/config.go
tar --strip-components=1 -C /home/jackylee/lede/build_dir/target-aarch64_generic_musl/alist-3.4.0/public/dist -xzf /home/jackylee/lede/dl/alist-web-3.4.0.tar.gz
cp -fpR ./files/assets/. /home/jackylee/lede/build_dir/target-aarch64_generic_musl/alist-3.4.0/public/dist/assets/
cp: cannot stat './files/assets/.': No such file or directory
make[3]: *** [Makefile:110: /home/jackylee/lede/build_dir/target-aarch64_generic_musl/alist-3.4.0/.prepared_c3f9a823104a39df778f88eabfbe6498_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/jackylee/lede/feeds/small8/alist'
time: package/feeds/small8/alist/compile#0.22#0.08#0.70
    ERROR: package/feeds/small8/alist failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small8/alist/compile] Error 1
make[2]: Leaving directory '/home/jackylee/lede'
make[1]: *** [package/Makefile:110: /home/jackylee/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jackylee/lede'
make: *** [/home/jackylee/lede/include/toplevel.mk:230：world] 错误 2

**Comment by kenzok8** [comment]
No such file or directory 没有下载下来

**Comment by JackyLeeGM** [comment]
> No such file or directory 没有下载下来

大佬，这个怎么下载呢（抱歉哈，我是个半路出家的小白选手，问题肤浅了，请见谅~~~）
