### ISSUE TITLE
请问：这个是怎么回事

### ISSUE THREAD

**Issue by dongfangy2011** [kenzok8/small-package#7]
Updating feed 'small8' from 'https://github.com/kenzok8/small-package' ...
fatal: 无法找到远程引用 refs/heads/18.06
failed.

**Comment by kenzok8** [comment]
18.06与19.07分支删除了，取而代之是main了
feeds.conf.default里删除老的small8 那行代码
然后运行命令
sed -i '$a src-git small8 https://github.com/kenzok8/small-package' feeds.conf.default
./scripts/feeds clean
./scripts/feeds update -a
./scripts/feeds install -a
重新拉取就可以了

**Comment by dongfangy2011** [comment]
非常感谢
