### ISSUE TITLE
关于openwrt编译luci-app-adguardhome，执行文件路径错误的问题

### ISSUE THREAD

**Issue by sss132919** [kenzok8/small-package#76]
lean最新源码编译openwrt x86 加入最新的luci-app-adguardhome的插件，执行文件路径显示/usr/bin/AdGuardHome , 但是这个路径在ssh里查看了是个文件夹，导致无法启动，实测将路径修改为/usr/bin/AdGuardHome/AdGuardHome之后不论是更新还是启动都恢复正常，希望可以在源码端处理一下，不然每次都要手动修改感觉比较麻烦，特别是保留配置升级的情况下

**Comment by kenzok8** [comment]
重新拉取了luci-app-adguardhome，应该是内核启动与luci启动不同写法的错误，有空帮看看修复了没

**Comment by sss132919** [comment]
测试中
