### ISSUE TITLE
mosdns与luci-app-mosdns版本不匹配

### ISSUE THREAD

**Issue by lededev** [kenzok8/small-package#77]
现在mosdns的git主干更新到了版本V5，然而luci-app-mosdns支持的版本是V4，这两个版本的配置文件差异导致服务无法启动。

**Comment by kenzok8** [comment]
上游已更新，你看下修复了没

**Comment by lededev** [comment]
> 上游已更新，你看下修复了没

那个更新我看了下，只是服务器列表更新了，功能代码并没有动过，还是只能适配mosdns v4.5.3，和v5.0.x不兼容。

**Comment by lededev** [comment]
你的自动更新可以参考一下这个改动，从mosdns的v4分支抓最新的改动，而不是从主干，主干默认v5了。
https://github.com/QiuSimons/openwrt-mos/commit/792dfd44044dc6a1e89419c2e400edaf07b11bc6

**Comment by kenzok8** [comment]
内核与luci都换更新源了，谢谢

**Comment by lededev** [comment]
mosdns v4.5.3能适配原来的luci-app-mosdns版本，你这个新的app好像改动挺多的，启动不了啊。
我还停 在https://github.com/kenzok8/small-package/commit/d33b3e35eea92098b13232e50ac5be2f2eb57b6f 这个版本

**Comment by lededev** [comment]
https://github.com/QiuSimons/openwrt-mos 已经支持V5了
