### ISSUE TITLE
依赖缺失反馈

### ISSUE THREAD

**Issue by sss132919** [kenzok8/small-package#80]
WARNING: Makefile 'package/feeds/smallpackage/luci-app-cloudflarespeedtest/Makefile' has a dependency on 'cdnspeedtest', which does not exist
WARNING: Makefile 'package/feeds/smallpackage/luci-app-filebrowser/Makefile' has a dependency on 'filebrowser', which does not exist
WARNING: Makefile 'package/feeds/smallpackage/luci-app-netspeedtest/Makefile' has a dependency on 'homebox', which does not exist
WARNING: Makefile 'package/feeds/smallpackage/luci-app-v2raya/Makefile' has a dependency on 'v2raya', which does not exist

**Comment by kenzok8** [comment]
應該補齊了，謝謝
