### ISSUE TITLE
GitHub 将停止支持 svn，应停止使用 svn export

### ISSUE THREAD

**Issue by KevinMX** [kenzok8/small-package#81]
Source: [GitHub Blog / Sunsetting Subversion support](https://github.blog/2023-01-20-sunsetting-subversion-support/)

注意到 main.sh 中已定义 `git_sparse_clone` 函数，或许应该迁移过去。

~~没了 svn 之后拉单个文件夹真麻烦啊~~

**Comment by kenzok8** [comment]
謝謝，過了春節弄，新春快樂
