### ISSUE TITLE
大佬，luci-app-msd_lite编译进固件不显示，L大的源码，N1的固件

### ISSUE THREAD

**Issue by xuexiao-weizi** [kenzok8/small-package#82]
大佬，luci-app-msd_lite编译进固件不显示，L大的源码，N1的固件，确认已经编译进去了，但是就是菜单内不显示。

**Comment by xuexiao-weizi** [comment]
https://github.com/ximiTech/luci-app-msd_lite
https://github.com/ximiTech/msd_lite
把这两个拉过来试试，我看这俩个比较新

**Comment by kenzok8** [comment]
人家是换汤不换药，自己修改的，其实就是最后一次提交commit 的值a8c16319588bb0407ba3edc3ba367d4070ea32c3
https://github.com/rozhuk-im/msd_lite/commit/a8c16319588bb0407ba3edc3ba367d4070ea32c3
我看了天灵的
https://github.com/immortalwrt/packages/blob/master/net/msd_lite/Makefile
和L大的
https://github.com/coolsnowwolf/packages/blob/master/net/msd_lite/Makefile
![image](https://user-images.githubusercontent.com/39034242/215335907-f38f8607-4d85-49b9-be47-7f372f607975.png)
