### ISSUE TITLE
xray-core编译时出现问题

### ISSUE THREAD

**Issue by chunkingzou** [kenzok8/small-package#83]
Building targets
../../../../../dl/go-mod-cache/github.com/quic-go/qtls-go1-20@v0.1.0/handshake_client.go:11:2: package crypto/ecdh is not in GOROOT (/home/chunqing/lede/staging_dir/hostpkg/lib/go-cross/src/crypto/ecdh)

make[3]: *** [Makefile:52: /home/chunqing/lede/build_dir/target-aarch64_generic_musl/Xray-core-1.7.3/.built] Error 1
make[3]: Leaving directory '/home/chunqing/lede/feeds/small8/xray-core'
time: package/feeds/small8/xray-core/compile#1.32#1.07#2.42
    ERROR: package/feeds/small8/xray-core failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small8/xray-core/compile] Error 1
make[2]: Leaving directory '/home/chunqing/lede'
make[1]: *** [package/Makefile:110: /home/chunqing/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/chunqing/lede'
make: *** [/home/chunqing/lede/include/toplevel.mk:231：world] 错误 2
编译报错，已经排除网络问题了，这种该怎么解决？

**Comment by kenzok8** [comment]
[#367](https://github.com/kenzok8/openwrt-packages/issues/367#issuecomment-1413262280)
https://github.com/XTLS/Xray-core/issues/1592

**Comment by chunkingzou** [comment]
非常感谢

**Comment by smdx** [comment]
刚才云编译遇到同样问题

**Comment by kenzok8** [comment]
拉取一下，已经打了补丁了
