### ISSUE TITLE
还是luci-app-adguardhome的问题

### ISSUE THREAD

**Issue by sss132919** [kenzok8/small-package#86]
我又来了，还是luci-app-adguardhome的问题，最新版luci-app-adguardhome的工作目录路径是一个文件，默认是无法启用的，得自己手动修改为/usr/bin/AdGuardHomeData
而且在网页管理界面的修改是默认不生效的，只能在手动设置里修改配置文件才会生效
并且该luci-app-adguardhome好像将执行文件存储到了/tmp文件夹，这意味着只要关机重启就需要重新下载执行文件，很诡异
还请帮忙反馈或者处理一下，谢谢

**Comment by kenzok8** [comment]
首先确认下，是否编译源码里有AdGuardHome，如果有请删除了再编译下试试
其次，我前几天用Lean与Lienol 还有immortalwrt编译过，启动。更新啥的都没问题，前提我是删除源码自带的AdGuardHom与luci
如有问题再反馈

**Comment by sss132919** [comment]
> 首先确认下，是否编译源码里有AdGuardHome，如果有请删除了再编译下试试 其次，我前几天用Lean与Lienol 还有immortalwrt编译过，启动。更新啥的都没问题，前提我是删除源码自带的AdGuardHom与luci 如有问题再反馈

直接打开luci的界面，是需要更新adguardhome内核的，这应该意味着没有编译这个内核。更主要的是，Lean的源码默认是没有选中adguardhome的，如果没有添加此仓库，那么luci都找不到这个插件。
如果你的没问题，那我只能再测试一下了，但是希望不大

**Comment by kenzok8** [comment]
有的
https://github.com/coolsnowwolf/packages/tree/master/net/adguardhome
另外你编译的时候不是光选择luci的，你要把内核编译进去的
![image](https://user-images.githubusercontent.com/39034242/219846102-addf27b2-c426-46c6-a78f-6d8a6a3e7dd9.png)
还有就是你可以删除small-package的adguardhome，试着用Lean的编译，看看是否有问题

**Comment by sss132919** [comment]
> 有的 https://github.com/coolsnowwolf/packages/tree/master/net/adguardhome 另外你编译的时候不是光选择luci的，你要把内核编译进去的 ![image](https://user-images.githubusercontent.com/39034242/219846102-addf27b2-c426-46c6-a78f-6d8a6a3e7dd9.png) 还有就是你可以删除small-package的adguardhome，试着用Lean的编译，看看是否有问题

好的，我会尝试的，我是想如果仓库能够解决会更方便

**Comment by SakuraFallingMad** [comment]
> > 首先确认下，是否编译源码里有AdGuardHome，如果有请删除了再编译下试试 其次，我前几天用Lean与Lienol 还有immortalwrt编译过，启动。更新啥的都没问题，前提我是删除源码自带的AdGuardHom与luci 如有问题再反馈
> 
> 直接打开luci的界面，是需要更新adguardhome内核的，这应该意味着没有编译这个内核。更主要的是，Lean的源码默认是没有选中adguardhome的，如果没有添加此仓库，那么luci都找不到这个插件。 如果你的没问题，那我只能再测试一下了，但是希望不大

上个源的版本不错啊，我用immortalwrt的，他的package有二进制程序，再配套luci，可以正常使用

还是上一个源的luci-app-adguardhome比较好，这版本客制化味道太浓，而且最新编译的好像语言文件没有，都是英文的。
![image](https://user-images.githubusercontent.com/31793080/219951008-6caa51f9-247e-4c93-8d35-ad16e2878286.png)

**Comment by kenzok8** [comment]
![image](https://user-images.githubusercontent.com/39034242/219951393-22052d3b-9e9d-4850-b65b-434aee465dae.png)
中文是有的，不是说没法启动么，所以换了个上游仓库，如果不好用就换回原来的
![image](https://user-images.githubusercontent.com/39034242/219951496-b28f5d45-8454-49ef-97d9-f5a29a798455.png)

**Comment by SakuraFallingMad** [comment]
个人觉得上个看着比较干净，这个上游仓库，预置的yaml文件客制化太多了，还好我是升级固件的，都是自己配置，但是我瞄了一眼[ luci-app-adguardhome/root/etc/AdGuardHome.yaml](https://github.com/kenzok8/small-package/blob/fcd035f9466b24b226088d4329acea7951fff896/luci-app-adguardhome/root/etc/AdGuardHome.yaml)

**Comment by Pan5094** [comment]
看上去上个版本更新，但是需要修改核心路径

**Comment by sss132919** [comment]
执行./scripts/feeds install -a -f 之后会有这些waning
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'bc', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'lm-sensors', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'luci-app-samba4', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'wsdd2', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_aliyun/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_aliyun/Makefile' has a dependency on 'wget-ssl', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_dnspod/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_dnspod/Makefile' has a dependency on 'wget-ssl', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci-base', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/qat/libs/eudev/Makefile' has a dependency on 'libkmod', which does not exist
WARNING: Makefile 'package/qat/libs/eudev/Makefile' has a build dependency on 'gperf/host', which does not exist
WARNING: Makefile 'package/lean/ipv6-helper/Makefile' has a dependency on 'luci-proto-ipv6', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-gobinetmodem/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-gobinetmodem/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/mt/luci-app-mtwifi/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-pcimodem/Makefile' has a dependency on 'pciutils', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-pcimodem/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-spdmodem/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-usbmodem/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-usbmodem/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/mt/drivers/mt7615d/Makefile' has a dependency on 'maccalc', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libcurl', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libtins', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libyaml-cpp', which does not exist
WARNING: Makefile 'package/lean/pcat-manager/Makefile' has a dependency on 'glib2', which does not exist
WARNING: Makefile 'package/lean/pcat-manager/Makefile' has a dependency on 'libgpiod', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/firmware/quantenna/Makefile' has a dependency on 'libtirpc', which does not exist
WARNING: Makefile 'package/firmware/quantenna/Makefile' has a build dependency on 'libtirpc', which does not exist
WARNING: Makefile 'package/wwan/driver/quectel_MHI/Makefile' has a dependency on 'pciids', which does not exist
WARNING: Makefile 'package/wwan/driver/quectel_MHI/Makefile' has a dependency on 'pciutils', which does not exist
WARNING: Makefile 'package/network/services/samba36/Makefile' has a dependency on 'libaio', which does not exist
WARNING: Not overriding core package 'mbedtls'; use -f to force
WARNING: Not overriding core package 'mbedtls'; use -f to force
WARNING: Not overriding core package 'mbedtls'; use -f to force
WARNING: Not overriding core package 'upx'; use -f to force

**Comment by kenzok8** [comment]
兄弟你看下路径，好多都是package/lean/  package/utils/这些路径的错误，这个锅我不背！

**Comment by sss132919** [comment]
已修正。openwrt.org官方源码，执行./scripts/feeds install -a -f 之后会有这些waning
WARNING: Makefile 'package/feeds/small/amule/Makefile' has a dependency on 'libcryptopp', which does not exist
WARNING: Makefile 'package/feeds/small/amule/Makefile' has a build dependency on 'libcryptopp', which does not exist
WARNING: Makefile 'package/feeds/small/baidupcs-web/Makefile' has a build dependency on 'go-rice/host', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-fullconenat/Makefile' has a dependency on 'iptables-mod-fullconenat', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-tencentcloud-cos/Makefile' has a dependency on 'vsftpd-alt', which does not exist
