### ISSUE TITLE
你好大佬，UPX的HASH值不对

### ISSUE THREAD

**Issue by sss132919** [kenzok8/small-package#87]
你好大佬，upx的hash值好像没有修改，编译老是不通过，劳烦了

**Comment by kenzok8** [comment]
![image](https://user-images.githubusercontent.com/39034242/220704595-fac69256-56b4-42b1-a48f-1afe7df0ab5c.png)
如果你怀疑Hash值不对，你可以在Hash改成skip，对编译无影响，这个是防止文件被篡改校对而已

**Comment by sss132919** [comment]
> 

是的哦，4.0.2开头的软件版本，hash值不是54开头的，编译的时候是这样显示的，而且我发现最近老是遇到hash值对不上的问题，不光是这个仓库。不知道是什么情况

**Comment by kenzok8** [comment]
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION)-src.tar.xz
PKG_SOURCE_URL:=https://github.com/upx/upx/releases/download/v$(PKG_VERSION)
PKG_HASH:=skip
你可以手动这样修改，对编译没影响的

**Comment by sss132919** [comment]
还是upx的问题

make[3]: Entering directory '/home/mint/self/lede/feeds/small/upx'
mkdir -p /home/mint/self/lede/dl
SHELL= flock /home/mint/self/lede/tmp/.upx-4.0.2-src.tar.xz.flock -c '  	/home/mint/self/lede/scripts/download.pl "/home/mint/self/lede/dl" "upx-4.0.2-src.tar.xz" "skip" "" "https://github.com/upx/upx/releases/download/v4.0.2"    '
. /home/mint/self/lede/include/shell.sh; xzcat /home/mint/self/lede/dl/upx-4.0.2-src.tar.xz | tar -C /home/mint/self/lede/build_dir/hostpkg/upx-4.0.2/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/* /home/mint/self/lede/build_dir/hostpkg/upx-4.0.2
touch /home/mint/self/lede/build_dir/hostpkg/upx-4.0.2/.prepared9a183312ae6b8712e5b5a3973d81b316_6664517399ebbbc92a37c5bb081b5c53
(cd /home/mint/self/lede/build_dir/hostpkg/upx-4.0.2/; if [ -x configure ]; then cp -fpR /home/mint/self/lede/scripts/config.{guess,sub} /home/mint/self/lede/build_dir/hostpkg/upx-4.0.2// && CC="gcc" CFLAGS="-O2 -I/home/mint/self/lede/staging_dir/host/include -I/home/mint/self/lede/staging_dir/hostpkg/include -I/home/mint/self/lede/staging_dir/target-x86_64_musl/host/include" CXX="g++" CPPFLAGS="-I/home/mint/self/lede/staging_dir/host/include -I/home/mint/self/lede/staging_dir/hostpkg/include -I/home/mint/self/lede/staging_dir/target-x86_64_musl/host/include" CXXFLAGS="" LDFLAGS="-L/home/mint/self/lede/staging_dir/host/lib -L/home/mint/self/lede/staging_dir/hostpkg/lib -L/home/mint/self/lede/staging_dir/target-x86_64_musl/host/lib" CONFIG_SHELL="/usr/bin/env bash"  bash ./configure --target=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/home/mint/self/lede/staging_dir/hostpkg --exec-prefix=/home/mint/self/lede/staging_dir/hostpkg --sysconfdir=/home/mint/self/lede/staging_dir/hostpkg/etc --localstatedir=/home/mint/self/lede/staging_dir/hostpkg/var --sbindir=/home/mint/self/lede/staging_dir/hostpkg/bin ; fi )
touch /home/mint/self/lede/build_dir/hostpkg/upx-4.0.2/.configured
UPX_UCLDIR=/home/mint/self/lede/staging_dir/host make -C /home/mint/self/lede/build_dir/hostpkg/upx-4.0.2/src LDFLAGS="-L/home/mint/self/lede/staging_dir/host/lib -L/home/mint/self/lede/staging_dir/hostpkg/lib -L/home/mint/self/lede/staging_dir/target-x86_64_musl/host/lib" CXX="g++"
make[4]: *** /home/mint/self/lede/build_dir/hostpkg/upx-4.0.2/src: No such file or directory.  Stop.
make[3]: *** [Makefile:61: /home/mint/self/lede/build_dir/hostpkg/upx-4.0.2/.built] Error 2
make[3]: Leaving directory '/home/mint/self/lede/feeds/small/upx'
time: package/feeds/small/upx/host-compile#0.19#0.04#0.28
    ERROR: package/feeds/small/upx [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/small/upx/host/compile] Error 1
make[2]: Leaving directory '/home/mint/self/lede'
make[1]: *** [package/Makefile:110: /home/mint/self/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/mint/self/lede'
make: *** [/home/mint/self/lede/include/toplevel.mk:231：world] 错误 2
不知道是出了什么问题，git pull之后就一直提示这个错误
