### ISSUE TITLE
luci-theme-neobird

### ISSUE THREAD

**Issue by aoxijy** [kenzok8/small-package#89]
luci-theme-neobird   这个主题挺不错，不知道为什么没有收录， 能收录一下这个主题吗。 谢谢
主题地址：https://github.com/thinktip/luci-theme-neobird

**Comment by kenzok8** [comment]
几天前刚刚删除，[luci-theme-design](https://github.com/kenzok8/openwrt-packages/tree/master/luci-theme-design)这个其实类似的，而且还有支持js版本的（luci-21）
https://github.com/kenzok8/AutoSync/commit/4a7f341fdc746459a55851fc99310618dda99b69

**Comment by aoxijy** [comment]
好的 我也看见了，只是太黑化，不过也还可以， 谢谢！

**Comment by KevinMX** [comment]
> 几天前刚刚删除，[luci-theme-design](https://github.com/kenzok8/openwrt-packages/tree/master/luci-theme-design)这个其实类似的，而且还有支持js版本的（luci-21） [kenzok8/AutoSync@4a7f341](https://github.com/kenzok8/AutoSync/commit/4a7f341fdc746459a55851fc99310618dda99b69)

design 主题底栏默认是 OpenClash，neobird 底栏是 ssr-plus，对于不用 OpenClash 的用户这个主题会有点鸡肋……其实保留也行。不过 Lean lede 已经合并了，无所谓咯。

Update: 这个问题已经解决了，https://github.com/gngpp/luci-app-design-config
