### ISSUE TITLE
luci-app-dnscrypt-proxy2这个包依赖minisign，make download V=s的时候找不到要紧吗？

### ISSUE THREAD

**Issue by xiaopang0v0** [kenzok8/small-package#9]
在make download V=s的时候看到的警告
WARNING: Makefile 'package/feeds/smallpackage/luci-app-dnscrypt-proxy2/Makefile' has a dependency on 'minisign', which does not exist
请问这个要紧吗？

**Comment by Thanf-code** [comment]
> 在make download V=s的时候看到的警告 WARNING: Makefile 'package/feeds/smallpackage/luci-app-dnscrypt-proxy2/Makefile' has a dependency on 'minisign', which does not exist 请问这个要紧吗？

那要看你是否选择该插件了，如果选择编译这个插件就有影响，会编译失败。如果不选择该插件进行编译就没影响

**Comment by SterlingCarter** [comment]
> 在make download V=s的时候看到的警告 WARNING: Makefile 'package/feeds/smallpackage/luci-app-dnscrypt-proxy2/Makefile' has a dependency on 'minisign', which does not exist 请问这个要紧吗？

我也是总是报这个警告
![QQ图片20211201161011](https://user-images.githubusercontent.com/66172871/144196396-3c9a1704-3832-4d0d-a7bb-f4707707d37b.png)
