### ISSUE TITLE
luci-app-adguardhome 无中文界面

### ISSUE THREAD

**Issue by SakuraFallingMad** [kenzok8/small-package#90]
应该是luci-app-adguardhome/po/zh_Hans的符号链接问题导致的
![image](https://user-images.githubusercontent.com/31793080/222950773-745059d1-5572-4a96-a682-1ea33318630b.png)

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small-package/commit/45a25a29bcd2e1a13382687bf50b98c5e31a6c27
