### ISSUE TITLE
编译 upx失败

### ISSUE THREAD

**Issue by davidtall** [kenzok8/small-package#91]
```
. /home/www/lede/include/shell.sh; xzcat /home/www/lede/dl/upx-4.0.2-src.tar.xz | tar -C /home/www/lede/build_dir/hostpkg/upx-4.0.2/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/* /home/www/lede/build_dir/hostpkg/upx-4.0.2
touch /home/www/lede/build_dir/hostpkg/upx-4.0.2/.prepared030433674b6aca78522fb880240db9e0_6664517399ebbbc92a37c5bb081b5c53
(cd /home/www/lede/build_dir/hostpkg/upx-4.0.2/; if [ -x configure ]; then cp -fpR /home/www/lede/scripts/config.{guess,sub} /home/www/lede/build_dir/hostpkg/upx-4.0.2// && CC="gcc" CFLAGS="-O2 -I/home/www/lede/staging_dir/host/include -I/home/www/lede/staging_dir/hostpkg/include -I/home/www/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/include" CXX="g++" CPPFLAGS="-I/home/www/lede/staging_dir/host/include -I/home/www/lede/staging_dir/hostpkg/include -I/home/www/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/include" CXXFLAGS="" LDFLAGS="-L/home/www/lede/staging_dir/host/lib -L/home/www/lede/staging_dir/hostpkg/lib -L/home/www/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/lib" CONFIG_SHELL="/usr/bin/env bash"  bash ./configure --target=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/home/www/lede/staging_dir/hostpkg --exec-prefix=/home/www/lede/staging_dir/hostpkg --sysconfdir=/home/www/lede/staging_dir/hostpkg/etc --localstatedir=/home/www/lede/staging_dir/hostpkg/var --sbindir=/home/www/lede/staging_dir/hostpkg/bin ; fi )
touch /home/www/lede/build_dir/hostpkg/upx-4.0.2/.configured
UPX_UCLDIR=/home/www/lede/staging_dir/host make -C /home/www/lede/build_dir/hostpkg/upx-4.0.2/src LDFLAGS="-L/home/www/lede/staging_dir/host/lib -L/home/www/lede/staging_dir/hostpkg/lib -L/home/www/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/lib" CXX="g++"
make[4]: *** /home/www/lede/build_dir/hostpkg/upx-4.0.2/src: No such file or directory.  Stop.
make[3]: *** [Makefile:61: /home/www/lede/build_dir/hostpkg/upx-4.0.2/.built] Error 2
make[3]: Leaving directory '/home/www/lede/package/small-package/upx'
time: package/small-package/upx/host-compile#0.36#0.14#4.21
    ERROR: package/small-package/upx [host] failed to build.
make[2]: *** [package/Makefile:114: package/small-package/upx/host/compile] Error 1
make[2]: Leaving directory '/home/www/lede'
make[1]: *** [package/Makefile:110: /home/www/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/www/lede'
make[1]: Leaving directory '/home/www/lede'
make: *** [/home/www/lede/include/toplevel.mk:231: world] Error 2

```

make[4]: *** /home/www/lede/build_dir/hostpkg/upx-4.0.2/src: No such file or directory.  Stop.
这一行，我看了4.0.2 版本压缩包解压出来的路径是 upx-4.0.2-src,所以导致找不到路径，请问应该如何修正这个问题？

https://github.com/kenzok8/small-package/blob/main/upx/Makefile 
看这个Makefile 不是很懂

**Comment by kenzok8** [comment]
先dl文件夹里看下是否有拉取upx-4.0.2-src.tar.xz，如果没有就是网络问题
另外如果文件在。我不知道你是用什么源码编译，是否有另外的upx冲突
比如Lienol大的 rm -rf tools/upx && cp -Rf feeds/smpackage/upx tools/upx
默认在tools路径下，有些在feeds/packages/utils目录下

**Comment by davidtall** [comment]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/9320941/223085012-76eab7b4-d9d2-4944-b334-e07943ace38a.png">
使用lean的源码编译的，我解压这个压缩包，里面的文件夹名字是upx-4.0.2-src，在官方下载 https://github.com/upx/upx/releases/ 也是这个路径，所以不确定是不是路径写错了

**Comment by kenzok8** [comment]
<img width="469" alt="1678099404675" src="https://user-images.githubusercontent.com/39034242/223088280-2da779a9-4989-4fc8-ae6e-f49b5258c712.png">

**Comment by davidtall** [comment]
我改用了Lienol 的源码，
1、按照你的方法 rm -rf tools/upx && cp -Rp package/small-package/upx tools/upx ，问题依旧 。
2、于是我删除 rm -rf package/small-package/upx ，问题依旧。
3、接着我还原Lienol 默认的版本3.9.5 到tools/upx ，删除   rm -rf package/small-package/upx ，不再报这个错误了
4、但是编译 mosdns失败，  报了一个note: module requires Go 1.19 ，去看mosdns官方github 也是提示5.1.2版本需要go1.19 编译，而 Lienol默认的版本是1.18 ， 于是我修改 feeds/packages/lang/golang/golang/Makefile  版本为1.19.7 ，编译成功。
5、但我还搞不明白为何 upx 4.0.2会编译失败

**Comment by kenzok8** [comment]
你现在golang 替换成1.19版本了，然后用upx 4.0.2编译失败吗？

**Comment by davidtall** [comment]
我把 upx 4.0.2 复制到 tools/upx 下重新编译也是成功的，是不是要make dirclean 重新来一遍？可能编译成功了就不会编译这个依赖了

**Comment by kenzok8** [comment]
嗯，有时间可以尝试下，因为我用Lienol的云编译也替换了upx，顺带编译了mosdns没报错

**Comment by davidtall** [comment]
另外这个仓库的luci-app-mosdns 支持最新的mosdns V5 版本吗？我找不到源仓库， https://github.com/sbwml/luci-app-mosdns这个好像又不是，版本号对不上，而且目前只支持V4

**Comment by kenzok8** [comment]
https://github.com/QiuSimons/openwrt-mos
就是v5版本，他编译内核时调用了upx压缩
https://github.com/kenzok8/small-package/blob/main/mosdns/Makefile

**Comment by davidtall** [comment]
我刚刚测试， 重新拉取源码 ， 复制upx 4.0.2  tools/upx ，删除 package/small-package/upx ，是可以编译成功的。这样看的确是冲突问题了，多谢指点！另外请教一个问题，lean和Lienol还有immortalwrt的源码都支持 这个small插件仓库吗？这三个版本有什么区别吗？我看Lienol的源码有22.03的版本，是不是Lienol 更接近官方openwrt 如果为了尝新就用Lienol的？

**Comment by kenzok8** [comment]
说不上谁好，Lienol的本身不错，插件 多肯定bug更多，主要是稳定，我都一年多没更新固件了

**Comment by davidtall** [comment]
我用lean的源 替换lede/package/lean/upx 为 4.0.2版本，还是会出现同样的问题，删除4.0.2还原lean默认的版本才能编译成功

**Comment by davidtall** [comment]
@kenzok8 还有个upx-static 这个是否也需要一起删除？
