### ISSUE TITLE
dockerd无法编译，提示Expected 'PKG_VERSION:=1.6.13' in '../containerd/Makefile', found 'PKG_VERSION:=

### ISSUE THREAD

**Issue by codercaizh** [kenzok8/small-package#93]
![image](https://user-images.githubusercontent.com/17381647/226252564-65f525a3-5da6-42d4-becc-c138baa886a6.png)
日志如上，看起来好像是上游更新了这边没有同步更新

**Comment by kenzok8** [comment]
上游地址提供下
