### ISSUE TITLE
luci-app-adguardhome启动脚本丢失可执行权限，导致无法启动

### ISSUE THREAD

**Issue by quanjindeng** [kenzok8/small-package#94]
最近更新之后发现这个插件无法启动了，需要手动赋予可执行权限
chmod +x /usr/share/AdGuardHome/addhost.sh
chmod +x /etc/init.d/AdGuardHome
注意到最近的更新后，相关文件的权限从100755更改到了100644，应该是这个的原因

**Comment by quanjindeng** [comment]
还有/usr/share/AdGuardHome目录下的脚本应该都需要修复下权限问题

**Comment by kenzok8** [comment]
上游仓库作者的问题，所以Lienol的仓库里https://github.com/Lienol/openwrt/blob/22.03/package/default-settings/files/zzz-default-settings 加了chmod 0755 /etc/init.d/* 
因为我是自动同步，不是手动提交，所以上述命令一劳永逸，防止init.d目录下权限问题
