### ISSUE TITLE
naiveproxy-111.0.5563.64-1编译报错

### ISSUE THREAD

**Issue by ghost** [kenzok8/small-package#95]
make[3]: Entering directory '/home/user/Desktop/leans-lede-ipq/feeds/small8/naiveproxy'
touch /home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/.prepared_5b69bff41b62ff5701c4c804200e1e9c_6664517399ebbbc92a37c5bb081b5c53_check
. /home/user/Desktop/leans-lede-ipq/include/shell.sh; /home/user/Desktop/leans-lede-ipq/staging_dir/host/bin/libdeflate-gzip -dc /home/user/Desktop/leans-lede-ipq/dl/naiveproxy-111.0.5563.64-1.tar.gz | tar -C /home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1

Applying ./patches/100-macros.patch using plaintext: 
patching file src/base/allocator/partition_allocator/tagging.cc
( pushd /home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/src ; mkdir -p "chrome/build/pgo_profiles" ; cp -fpR "/home/user/Desktop/leans-lede-ipq/dl/chrome-linux-5563-1677886924-aa8d450a18b4f7f1cd41619f60bc5da6beb3c1d0.profdata" "chrome/build/pgo_profiles" ; mkdir -p "third_party/llvm-build/Release+Asserts" ; tar -xzf "/home/user/Desktop/leans-lede-ipq/dl/clang-llvmorg-16-init-17653-g39da55e8-2.tgz" -C "third_party/llvm-build/Release+Asserts" ; echo -e "llvmorg-16-init-17653-g39da55e8-2" > "third_party/llvm-build/Release+Asserts/cr_build_revision" ; popd ; )
~/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/src ~/Desktop/leans-lede-ipq/feeds/small8/naiveproxy
~/Desktop/leans-lede-ipq/feeds/small8/naiveproxy
touch /home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/.prepared_5b69bff41b62ff5701c4c804200e1e9c_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/.configured_*
rm -f /home/user/Desktop/leans-lede-ipq/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.naiveproxy_installed
( pushd "/home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/src" ; . ../init_env.sh "arm" "cortex-a7" "neon-vfpv4" "/home/user/Desktop/leans-lede-ipq/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi" ; export naive_flags+=" ${naive_ccache_flags}" ; mkdir -p "out" ; gn gen "out/Release" --args="${naive_flags}" --script-executable="python3" ; popd ; )
~/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/src ~/Desktop/leans-lede-ipq/feeds/small8/naiveproxy
bash: line 1: gn: command not found
~/Desktop/leans-lede-ipq/feeds/small8/naiveproxy
touch /home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/.built
touch /home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/.built_check
ninja -C "/home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/src/out/Release" naive
ninja: Entering directory `/home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/src/out/Release'
ninja: fatal: chdir to '/home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/src/out/Release' - No such file or directory
make[3]: *** [Makefile:119: /home/user/Desktop/leans-lede-ipq/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/naiveproxy-111.0.5563.64-1/.built] Error 1
make[3]: Leaving directory '/home/user/Desktop/leans-lede-ipq/feeds/small8/naiveproxy'
time: package/feeds/small8/naiveproxy/compile#3.57#2.83#6.24
    ERROR: package/feeds/small8/naiveproxy failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small8/naiveproxy/compile] Error 1
make[2]: Leaving directory '/home/user/Desktop/leans-lede-ipq'
make[1]: *** [package/Makefile:110: /home/user/Desktop/leans-lede-ipq/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/user/Desktop/leans-lede-ipq'
make: *** [/home/user/Desktop/leans-lede-ipq/include/toplevel.mk:231：world] 错误 2

已参考 [378](https://github.com/kenzok8/openwrt-packages/issues/378) ，下面两个方案依旧报错

方案一：
make distclean
git pull && ./scripts/feeds update -a && ./scripts/feeds install -a
方案二：删掉整个目录重新拉取源码

**Comment by kenzok8** [comment]
这个仓库与[378](https://github.com/kenzok8/openwrt-packages/issues/378) 的仓库版本不一样，
这个仓库的naiveproxy-111.0.5563.64-1是新的，编译出错也很明细 gn: command not found
我刚刚补充gn了，git pull 下，看是否还报错

**Comment by ghost** [comment]
> 这个仓库与[378](https://github.com/kenzok8/openwrt-packages/issues/378) 的仓库版本不一样， 这个仓库的naiveproxy-111.0.5563.64-1是新的，编译出错也很明细 gn: command not found 我刚刚补充gn了，git pull 下，看是否还报错

问题已解决 （删掉lede目录，重新拉一遍源码）
