### ISSUE TITLE
对于编译版本有些疑问想请教

### ISSUE THREAD

**Issue by aceslup** [kenzok8/small-package#96]
使用云编译，拉取最新插件代码，最近几次luci-app-aliyundrive-webdav编译出来的版本都是1.11.0，我看最新源码已经到2.1.0了。请教一下，是需要做什么特殊操作吗？打扰了

以下是添加插件源的命令
`sed -i '$a src-git smpackage https://github.com/kenzok8/small-package' feeds.conf.default`

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small-package/issues/96#issue-1647103521
源码里可能有aliyundrive-webdav，默认内核编译了源码的aliyundrive-webdav了，请检查源码aliyundrive-webdav的路径，删除即可

**Comment by aceslup** [comment]
看了眼lean源码，没找着aliyundrive-webdav这部分源码，还会有其他原因不

 [https://github.com/coolsnowwolf/lede](url)

**Comment by kenzok8** [comment]
https://github.com/coolsnowwolf/packages/tree/master/multimedia
有的，git pull了后有这个的，你去lede下找到package/multimedia下面

Aceslup ***@***.***>于2023年3月31日 周五15:58写道：

**Comment by aceslup** [comment]
我看得太不仔细了，感谢指点。还能再多问2个问题吗？
1. feeds.conf.default文件中，把 kenzok8/small-package 添加在 coolsnowwolf/packages 之前，如有冲突的话，会优先使用你的源么
2. 如果问题1行不通，以下两步哪个正确呢：
    A. 先 feeds update，再清理冲突源码，再进行 feeds install；
    B. 或者是需要先 feeds update，清理冲突源码，再feeds update，再进行feeds install。

**Comment by kenzok8** [comment]
首先 ./scripts/feeds update -a 
删除冲突的（比如保留我仓库的最新插件）
再 ./scripts/feeds install -a

另外添加eeds.conf.default文件，调整安装顺序应该是可以的

**Comment by aceslup** [comment]
> 首先 ./scripts/feeds update -a 删除冲突的（比如保留我仓库的最新插件） 再 ./scripts/feeds install -a
> 
> 另外添加eeds.conf.default文件，调整安装顺序应该是可以的

好的，感谢回复。前段时间lede源码编译出现pppoe拨号问题，还不晓得测试所提的步骤方案是否成功。我立刻尝试。
