### ISSUE TITLE
你好大佬 新的naiveproxy-112.0.5615.49-1 编译提示找不到路径。。。

### ISSUE THREAD

**Issue by ppyohhh** [kenzok8/small-package#98]
ninja: Entering directory `/home/u/lede/build_dir/target-x86_64_musl/naiveproxy-112.0.5615.49-1/src/out/Release'

ninja: error: loading 'build.ninja': No such file or directory

make[3]: *** [Makefile:119: /home/u/lede/build_dir/target-x86_64_musl/naiveproxy-112.0.5615.49-1/.built] Error 1

**Comment by kenzok8** [comment]
https://github.com/ninja-build/ninja/releases/tag/v1.11.1

**Comment by 596142041** [comment]
> https://github.com/ninja-build/ninja/releases/tag/v1.11.1
这文件下载之后是放在DL文件夹里面么

**Comment by ppyohhh** [comment]
> > https://github.com/ninja-build/ninja/releases/tag/v1.11.1
> > 这文件下载之后是放在DL文件夹里面么

额 环境里有ninja 这个。。。但是编译还是提示   是不是因为这个naiveproxy插件缘故。。。。

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small-package/commit/8eba459ec2cd984674eee7c4cfde7d68182bd097
